// frontend/app/stocks.ts
// NSE BATCH 1 (125 Stocks)

const RAW_STOCKS = [
  // Financials & Banks
  { name: 'HDFC Bank', symbol: 'HDFCBANK', exchange: 'NSE', ticker: 'HDFCBANK.NS', currency: '₹' },
  { name: 'ICICI Bank', symbol: 'ICICIBANK', exchange: 'NSE', ticker: 'ICICIBANK.NS', currency: '₹' },
  { name: 'State Bank of India', symbol: 'SBIN', exchange: 'NSE', ticker: 'SBIN.NS', currency: '₹' },
  { name: 'Axis Bank', symbol: 'AXISBANK', exchange: 'NSE', ticker: 'AXISBANK.NS', currency: '₹' },
  { name: 'Kotak Mahindra', symbol: 'KOTAKBANK', exchange: 'NSE', ticker: 'KOTAKBANK.NS', currency: '₹' },
  { name: 'IndusInd Bank', symbol: 'INDUSINDBK', exchange: 'NSE', ticker: 'INDUSINDBK.NS', currency: '₹' },
  { name: 'Bank of Baroda', symbol: 'BANKBARODA', exchange: 'NSE', ticker: 'BANKBARODA.NS', currency: '₹' },
  { name: 'Punjab National Bank', symbol: 'PNB', exchange: 'NSE', ticker: 'PNB.NS', currency: '₹' },
  { name: 'Canara Bank', symbol: 'CANBK', exchange: 'NSE', ticker: 'CANBK.NS', currency: '₹' },
  { name: 'IDFC First Bank', symbol: 'IDFCFIRSTB', exchange: 'NSE', ticker: 'IDFCFIRSTB.NS', currency: '₹' },
  { name: 'Federal Bank', symbol: 'FEDERALBNK', exchange: 'NSE', ticker: 'FEDERALBNK.NS', currency: '₹' },
  { name: 'Bandhan Bank', symbol: 'BANDHANBNK', exchange: 'NSE', ticker: 'BANDHANBNK.NS', currency: '₹' },
  { name: 'Bajaj Finance', symbol: 'BAJFINANCE', exchange: 'NSE', ticker: 'BAJFINANCE.NS', currency: '₹' },
  { name: 'Bajaj Finserv', symbol: 'BAJAJFINSV', exchange: 'NSE', ticker: 'BAJAJFINSV.NS', currency: '₹' },
  { name: 'Cholamandalam Inv', symbol: 'CHOLAFIN', exchange: 'NSE', ticker: 'CHOLAFIN.NS', currency: '₹' },
  { name: 'Shriram Finance', symbol: 'SHRIRAMFIN', exchange: 'NSE', ticker: 'SHRIRAMFIN.NS', currency: '₹' },
  { name: 'Muthoot Finance', symbol: 'MUTHOOTFIN', exchange: 'NSE', ticker: 'MUTHOOTFIN.NS', currency: '₹' },
  { name: 'PFC', symbol: 'PFC', exchange: 'NSE', ticker: 'PFC.NS', currency: '₹' },
  { name: 'REC Ltd', symbol: 'RECLTD', exchange: 'NSE', ticker: 'RECLTD.NS', currency: '₹' },
  { name: 'SBI Cards', symbol: 'SBICARD', exchange: 'NSE', ticker: 'SBICARD.NS', currency: '₹' },

  // IT & Tech
  { name: 'TCS', symbol: 'TCS', exchange: 'NSE', ticker: 'TCS.NS', currency: '₹' },
  { name: 'Infosys', symbol: 'INFY', exchange: 'NSE', ticker: 'INFY.NS', currency: '₹' },
  { name: 'HCL Technologies', symbol: 'HCLTECH', exchange: 'NSE', ticker: 'HCLTECH.NS', currency: '₹' },
  { name: 'Wipro', symbol: 'WIPRO', exchange: 'NSE', ticker: 'WIPRO.NS', currency: '₹' },
  { name: 'Tech Mahindra', symbol: 'TECHM', exchange: 'NSE', ticker: 'TECHM.NS', currency: '₹' },
  { name: 'LTIMindtree', symbol: 'LTIM', exchange: 'NSE', ticker: 'LTIM.NS', currency: '₹' },
  { name: 'Coforge', symbol: 'COFORGE', exchange: 'NSE', ticker: 'COFORGE.NS', currency: '₹' },
  { name: 'Persistent Systems', symbol: 'PERSISTENT', exchange: 'NSE', ticker: 'PERSISTENT.NS', currency: '₹' },
  { name: 'Mphasis', symbol: 'MPHASIS', exchange: 'NSE', ticker: 'MPHASIS.NS', currency: '₹' },
  { name: 'L&T Technology Services', symbol: 'LTTS', exchange: 'NSE', ticker: 'LTTS.NS', currency: '₹' },

  // Auto & Auto Components
  { name: 'Tata Motors', symbol: 'TATAMOTORS', exchange: 'NSE', ticker: 'TATAMOTORS.NS', currency: '₹' },
  { name: 'Maruti Suzuki', symbol: 'MARUTI', exchange: 'NSE', ticker: 'MARUTI.NS', currency: '₹' },
  { name: 'Mahindra & Mahindra', symbol: 'M&M', exchange: 'NSE', ticker: 'M&M.NS', currency: '₹' },
  { name: 'Bajaj Auto', symbol: 'BAJAJ-AUTO', exchange: 'NSE', ticker: 'BAJAJ-AUTO.NS', currency: '₹' },
  { name: 'Eicher Motors', symbol: 'EICHERMOT', exchange: 'NSE', ticker: 'EICHERMOT.NS', currency: '₹' },
  { name: 'Hero MotoCorp', symbol: 'HEROMOTOCO', exchange: 'NSE', ticker: 'HEROMOTOCO.NS', currency: '₹' },
  { name: 'TVS Motor', symbol: 'TVSMOTOR', exchange: 'NSE', ticker: 'TVSMOTOR.NS', currency: '₹' },
  { name: 'Ashok Leyland', symbol: 'ASHOKLEY', exchange: 'NSE', ticker: 'ASHOKLEY.NS', currency: '₹' },
  { name: 'Escorts Kubota', symbol: 'ESCORTS', exchange: 'NSE', ticker: 'ESCORTS.NS', currency: '₹' },
  { name: 'Tube Investments', symbol: 'TIINDIA', exchange: 'NSE', ticker: 'TIINDIA.NS', currency: '₹' },
  { name: 'Bosch Ltd', symbol: 'BOSCHLTD', exchange: 'NSE', ticker: 'BOSCHLTD.NS', currency: '₹' },
  { name: 'MRF', symbol: 'MRF', exchange: 'NSE', ticker: 'MRF.NS', currency: '₹' },
  { name: 'Balkrishna Industries', symbol: 'BALKRISIND', exchange: 'NSE', ticker: 'BALKRISIND.NS', currency: '₹' },
  { name: 'Samvardhana Motherson', symbol: 'MOTHERSON', exchange: 'NSE', ticker: 'MOTHERSON.NS', currency: '₹' },
  { name: 'Cummins India', symbol: 'CUMMINSIND', exchange: 'NSE', ticker: 'CUMMINSIND.NS', currency: '₹' },

  // FMCG & Consumer Goods
  { name: 'ITC Ltd', symbol: 'ITC', exchange: 'NSE', ticker: 'ITC.NS', currency: '₹' },
  { name: 'Hindustan Unilever', symbol: 'HINDUNILVR', exchange: 'NSE', ticker: 'HINDUNILVR.NS', currency: '₹' },
  { name: 'Nestle India', symbol: 'NESTLEIND', exchange: 'NSE', ticker: 'NESTLEIND.NS', currency: '₹' },
  { name: 'Britannia', symbol: 'BRITANNIA', exchange: 'NSE', ticker: 'BRITANNIA.NS', currency: '₹' },
  { name: 'Tata Consumer', symbol: 'TATACONSUM', exchange: 'NSE', ticker: 'TATACONSUM.NS', currency: '₹' },
  { name: 'Dabur India', symbol: 'DABUR', exchange: 'NSE', ticker: 'DABUR.NS', currency: '₹' },
  { name: 'Godrej Consumer', symbol: 'GODREJCP', exchange: 'NSE', ticker: 'GODREJCP.NS', currency: '₹' },
  { name: 'Marico', symbol: 'MARICO', exchange: 'NSE', ticker: 'MARICO.NS', currency: '₹' },
  { name: 'Colgate Palmolive', symbol: 'COLPAL', exchange: 'NSE', ticker: 'COLPAL.NS', currency: '₹' },
  { name: 'Varun Beverages', symbol: 'VBL', exchange: 'NSE', ticker: 'VBL.NS', currency: '₹' },
  { name: 'United Breweries', symbol: 'UBL', exchange: 'NSE', ticker: 'UBL.NS', currency: '₹' },
  { name: 'United Spirits', symbol: 'MCDOWELL-N', exchange: 'NSE', ticker: 'MCDOWELL-N.NS', currency: '₹' },
  { name: 'Balrampur Chini', symbol: 'BALRAMCHIN', exchange: 'NSE', ticker: 'BALRAMCHIN.NS', currency: '₹' },
  { name: 'Radico Khaitan', symbol: 'RADICO', exchange: 'NSE', ticker: 'RADICO.NS', currency: '₹' },
  { name: 'Emami', symbol: 'EMAMILTD', exchange: 'NSE', ticker: 'EMAMILTD.NS', currency: '₹' },

  // Pharma & Healthcare
  { name: 'Sun Pharma', symbol: 'SUNPHARMA', exchange: 'NSE', ticker: 'SUNPHARMA.NS', currency: '₹' },
  { name: 'Dr. Reddys Labs', symbol: 'DRREDDY', exchange: 'NSE', ticker: 'DRREDDY.NS', currency: '₹' },
  { name: 'Cipla', symbol: 'CIPLA', exchange: 'NSE', ticker: 'CIPLA.NS', currency: '₹' },
  { name: 'Divis Labs', symbol: 'DIVISLAB', exchange: 'NSE', ticker: 'DIVISLAB.NS', currency: '₹' },
  { name: 'Apollo Hospitals', symbol: 'APOLLOHOSP', exchange: 'NSE', ticker: 'APOLLOHOSP.NS', currency: '₹' },
  { name: 'Lupin', symbol: 'LUPIN', exchange: 'NSE', ticker: 'LUPIN.NS', currency: '₹' },
  { name: 'Torrent Pharma', symbol: 'TORNTPHARM', exchange: 'NSE', ticker: 'TORNTPHARM.NS', currency: '₹' },
  { name: 'Zydus Lifesciences', symbol: 'ZYDUSLIFE', exchange: 'NSE', ticker: 'ZYDUSLIFE.NS', currency: '₹' },
  { name: 'Aurobindo Pharma', symbol: 'AUROPHARMA', exchange: 'NSE', ticker: 'AUROPHARMA.NS', currency: '₹' },
  { name: 'Biocon', symbol: 'BIOCON', exchange: 'NSE', ticker: 'BIOCON.NS', currency: '₹' },
  { name: 'Syngene', symbol: 'SYNGENE', exchange: 'NSE', ticker: 'SYNGENE.NS', currency: '₹' },
  { name: 'Max Healthcare', symbol: 'MAXHEALTH', exchange: 'NSE', ticker: 'MAXHEALTH.NS', currency: '₹' },
  { name: 'Glenmark', symbol: 'GLENMARK', exchange: 'NSE', ticker: 'GLENMARK.NS', currency: '₹' },
  { name: 'Laurus Labs', symbol: 'LAURUSLABS', exchange: 'NSE', ticker: 'LAURUSLABS.NS', currency: '₹' },
  { name: 'Granules India', symbol: 'GRANULES', exchange: 'NSE', ticker: 'GRANULES.NS', currency: '₹' },

  // Energy, Oil & Gas
  { name: 'Reliance Industries', symbol: 'RELIANCE', exchange: 'NSE', ticker: 'RELIANCE.NS', currency: '₹' },
  { name: 'ONGC', symbol: 'ONGC', exchange: 'NSE', ticker: 'ONGC.NS', currency: '₹' },
  { name: 'NTPC', symbol: 'NTPC', exchange: 'NSE', ticker: 'NTPC.NS', currency: '₹' },
  { name: 'Power Grid', symbol: 'POWERGRID', exchange: 'NSE', ticker: 'POWERGRID.NS', currency: '₹' },
  { name: 'Coal India', symbol: 'COALINDIA', exchange: 'NSE', ticker: 'COALINDIA.NS', currency: '₹' },
  { name: 'Tata Power', symbol: 'TATAPOWER', exchange: 'NSE', ticker: 'TATAPOWER.NS', currency: '₹' },
  { name: 'Indraprastha Gas', symbol: 'IGL', exchange: 'NSE', ticker: 'IGL.NS', currency: '₹' },
  { name: 'Mahanagar Gas', symbol: 'MGL', exchange: 'NSE', ticker: 'MGL.NS', currency: '₹' },
  { name: 'GAIL', symbol: 'GAIL', exchange: 'NSE', ticker: 'GAIL.NS', currency: '₹' },
  { name: 'BPCL', symbol: 'BPCL', exchange: 'NSE', ticker: 'BPCL.NS', currency: '₹' },
  { name: 'HPCL', symbol: 'HINDPETRO', exchange: 'NSE', ticker: 'HINDPETRO.NS', currency: '₹' },
  { name: 'IOCL', symbol: 'IOC', exchange: 'NSE', ticker: 'IOC.NS', currency: '₹' },

  // Metals & Mining
  { name: 'Tata Steel', symbol: 'TATASTEEL', exchange: 'NSE', ticker: 'TATASTEEL.NS', currency: '₹' },
  { name: 'JSW Steel', symbol: 'JSWSTEEL', exchange: 'NSE', ticker: 'JSWSTEEL.NS', currency: '₹' },
  { name: 'Hindalco', symbol: 'HINDALCO', exchange: 'NSE', ticker: 'HINDALCO.NS', currency: '₹' },
  { name: 'Vedanta', symbol: 'VEDL', exchange: 'NSE', ticker: 'VEDL.NS', currency: '₹' },
  { name: 'NMDC', symbol: 'NMDC', exchange: 'NSE', ticker: 'NMDC.NS', currency: '₹' },
  { name: 'SAIL', symbol: 'SAIL', exchange: 'NSE', ticker: 'SAIL.NS', currency: '₹' },
  { name: 'Jindal Steel', symbol: 'JINDALSTEL', exchange: 'NSE', ticker: 'JINDALSTEL.NS', currency: '₹' },
  { name: 'NALCO', symbol: 'NATIONALUM', exchange: 'NSE', ticker: 'NATIONALUM.NS', currency: '₹' },
  { name: 'Hindustan Zinc', symbol: 'HZL', exchange: 'NSE', ticker: 'HZL.NS', currency: '₹' },
  { name: 'APL Apollo Tubes', symbol: 'APLAPOLLO', exchange: 'NSE', ticker: 'APLAPOLLO.NS', currency: '₹' },

  // Infrastructure, Cement & Chemicals
  { name: 'Larsen & Toubro', symbol: 'LT', exchange: 'NSE', ticker: 'LT.NS', currency: '₹' },
  { name: 'UltraTech Cement', symbol: 'ULTRACEMCO', exchange: 'NSE', ticker: 'ULTRACEMCO.NS', currency: '₹' },
  { name: 'Grasim', symbol: 'GRASIM', exchange: 'NSE', ticker: 'GRASIM.NS', currency: '₹' },
  { name: 'Ambuja Cements', symbol: 'AMBUJACEM', exchange: 'NSE', ticker: 'AMBUJACEM.NS', currency: '₹' },
  { name: 'Shree Cement', symbol: 'SHREECEM', exchange: 'NSE', ticker: 'SHREECEM.NS', currency: '₹' },
  { name: 'ACC', symbol: 'ACC', exchange: 'NSE', ticker: 'ACC.NS', currency: '₹' },
  { name: 'Dalmia Bharat', symbol: 'DALBHARAT', exchange: 'NSE', ticker: 'DALBHARAT.NS', currency: '₹' },
  { name: 'Ramco Cements', symbol: 'RAMCOCEM', exchange: 'NSE', ticker: 'RAMCOCEM.NS', currency: '₹' },
  { name: 'Coromandel Int', symbol: 'COROMANDEL', exchange: 'NSE', ticker: 'COROMANDEL.NS', currency: '₹' },
  { name: 'PI Industries', symbol: 'PIIND', exchange: 'NSE', ticker: 'PIIND.NS', currency: '₹' },
  { name: 'SRF', symbol: 'SRF', exchange: 'NSE', ticker: 'SRF.NS', currency: '₹' },
  { name: 'Tata Chemicals', symbol: 'TATACHEM', exchange: 'NSE', ticker: 'TATACHEM.NS', currency: '₹' },
  { name: 'Deepak Nitrite', symbol: 'DEEPAKNTR', exchange: 'NSE', ticker: 'DEEPAKNTR.NS', currency: '₹' },
  { name: 'Navin Fluorine', symbol: 'NAVINFLUOR', exchange: 'NSE', ticker: 'NAVINFLUOR.NS', currency: '₹' },
  { name: 'Aarti Industries', symbol: 'AARTIIND', exchange: 'NSE', ticker: 'AARTIIND.NS', currency: '₹' },
  { name: 'Tata Elxsi', symbol: 'TATAELXSI', exchange: 'NSE', ticker: 'TATAELXSI.NS', currency: '₹' },
  { name: 'Linde India', symbol: 'LINDEINDIA', exchange: 'NSE', ticker: 'LINDEINDIA.NS', currency: '₹' },
  { name: 'UPL', symbol: 'UPL', exchange: 'NSE', ticker: 'UPL.NS', currency: '₹' },
  { name: 'Pidilite Industries', symbol: 'PIDILITIND', exchange: 'NSE', ticker: 'PIDILITIND.NS', currency: '₹' },
  { name: 'Gujarat Gas', symbol: 'GUJGASLTD', exchange: 'NSE', ticker: 'GUJGASLTD.NS', currency: '₹' },

  // Adani Group & Retail / New Tech
  { name: 'Adani Enterprises', symbol: 'ADANIENT', exchange: 'NSE', ticker: 'ADANIENT.NS', currency: '₹' },
  { name: 'Adani Ports', symbol: 'ADANIPORTS', exchange: 'NSE', ticker: 'ADANIPORTS.NS', currency: '₹' },
  { name: 'Adani Green', symbol: 'ADANIGREEN', exchange: 'NSE', ticker: 'ADANIGREEN.NS', currency: '₹' },
  { name: 'Adani Power', symbol: 'ADANIPOWER', exchange: 'NSE', ticker: 'ADANIPOWER.NS', currency: '₹' },
  { name: 'Adani Wilmar', symbol: 'AWL', exchange: 'NSE', ticker: 'AWL.NS', currency: '₹' },
  { name: 'Adani Total Gas', symbol: 'ATGL', exchange: 'NSE', ticker: 'ATGL.NS', currency: '₹' },
  { name: 'Trent', symbol: 'TRENT', exchange: 'NSE', ticker: 'TRENT.NS', currency: '₹' },
  { name: 'Avenue Supermarts (DMart)', symbol: 'DMART', exchange: 'NSE', ticker: 'DMART.NS', currency: '₹' },
  // frontend/app/stocks.ts
// NSE BATCH 2 (125 Stocks)

  // Midcap IT & Telecom
  { name: 'Tata Communications', symbol: 'TATACOMM', exchange: 'NSE', ticker: 'TATACOMM.NS', currency: '₹' },
  { name: 'Tata Elxsi', symbol: 'TATAELXSI', exchange: 'NSE', ticker: 'TATAELXSI.NS', currency: '₹' },
  { name: 'KPIT Technologies', symbol: 'KPITTECH', exchange: 'NSE', ticker: 'KPITTECH.NS', currency: '₹' },
  { name: 'Mphasis', symbol: 'MPHASIS', exchange: 'NSE', ticker: 'MPHASIS.NS', currency: '₹' },
  { name: 'Birlasoft', symbol: 'BSOFT', exchange: 'NSE', ticker: 'BSOFT.NS', currency: '₹' },
  { name: 'Cyient', symbol: 'CYIENT', exchange: 'NSE', ticker: 'CYIENT.NS', currency: '₹' },
  { name: 'Zensar Tech', symbol: 'ZENSARTECH', exchange: 'NSE', ticker: 'ZENSARTECH.NS', currency: '₹' },
  { name: 'Sonata Software', symbol: 'SONATSOFTW', exchange: 'NSE', ticker: 'SONATSOFTW.NS', currency: '₹' },
  { name: 'Vodafone Idea', symbol: 'IDEA', exchange: 'NSE', ticker: 'IDEA.NS', currency: '₹' },
  { name: 'Indus Towers', symbol: 'INDUSTOWER', exchange: 'NSE', ticker: 'INDUSTOWER.NS', currency: '₹' },

  // Defense, Aerospace & Shipyards
  { name: 'Hindustan Aeronautics', symbol: 'HAL', exchange: 'NSE', ticker: 'HAL.NS', currency: '₹' },
  { name: 'Bharat Electronics', symbol: 'BEL', exchange: 'NSE', ticker: 'BEL.NS', currency: '₹' },
  { name: 'Mazagon Dock', symbol: 'MAZDOCK', exchange: 'NSE', ticker: 'MAZDOCK.NS', currency: '₹' },
  { name: 'Cochin Shipyard', symbol: 'COCHINSHIP', exchange: 'NSE', ticker: 'COCHINSHIP.NS', currency: '₹' },
  { name: 'Garden Reach', symbol: 'GRSE', exchange: 'NSE', ticker: 'GRSE.NS', currency: '₹' },
  { name: 'Bharat Dynamics', symbol: 'BDL', exchange: 'NSE', ticker: 'BDL.NS', currency: '₹' },
  { name: 'BEML', symbol: 'BEML', exchange: 'NSE', ticker: 'BEML.NS', currency: '₹' },
  { name: 'MTAR Technologies', symbol: 'MTARTECH', exchange: 'NSE', ticker: 'MTARTECH.NS', currency: '₹' },
  { name: 'Data Patterns', symbol: 'DATAPATTNS', exchange: 'NSE', ticker: 'DATAPATTNS.NS', currency: '₹' },

  // Asset Management, Brokers & Exchanges
  { name: 'BSE Ltd', symbol: 'BSE', exchange: 'NSE', ticker: 'BSE.NS', currency: '₹' },
  { name: 'MCX India', symbol: 'MCX', exchange: 'NSE', ticker: 'MCX.NS', currency: '₹' },
  { name: 'CDSL', symbol: 'CDSL', exchange: 'NSE', ticker: 'CDSL.NS', currency: '₹' },
  { name: 'CAMS', symbol: 'CAMS', exchange: 'NSE', ticker: 'CAMS.NS', currency: '₹' },
  { name: 'Angel One', symbol: 'ANGELONE', exchange: 'NSE', ticker: 'ANGELONE.NS', currency: '₹' },
  { name: 'HDFC AMC', symbol: 'HDFCAMC', exchange: 'NSE', ticker: 'HDFCAMC.NS', currency: '₹' },
  { name: 'Nippon Life India', symbol: 'NAM-INDIA', exchange: 'NSE', ticker: 'NAM-INDIA.NS', currency: '₹' },
  { name: 'UTI AMC', symbol: 'UTIAMC', exchange: 'NSE', ticker: 'UTIAMC.NS', currency: '₹' },
  { name: 'Aditya Birla Capital', symbol: 'ABCAPITAL', exchange: 'NSE', ticker: 'ABCAPITAL.NS', currency: '₹' },
  { name: 'ICICI Securities', symbol: 'ISEC', exchange: 'NSE', ticker: 'ISEC.NS', currency: '₹' },

  // Insurance & Housing Finance
  { name: 'ICICI Lombard', symbol: 'ICICIGI', exchange: 'NSE', ticker: 'ICICIGI.NS', currency: '₹' },
  { name: 'Star Health', symbol: 'STARHEALTH', exchange: 'NSE', ticker: 'STARHEALTH.NS', currency: '₹' },
  { name: 'General Insurance', symbol: 'GICRE', exchange: 'NSE', ticker: 'GICRE.NS', currency: '₹' },
  { name: 'LIC Housing Finance', symbol: 'LICHSGFIN', exchange: 'NSE', ticker: 'LICHSGFIN.NS', currency: '₹' },
  { name: 'PNB Housing', symbol: 'PNBHOUSING', exchange: 'NSE', ticker: 'PNBHOUSING.NS', currency: '₹' },
  { name: 'Can Fin Homes', symbol: 'CANFINHOME', exchange: 'NSE', ticker: 'CANFINHOME.NS', currency: '₹' },
  { name: 'Aavas Financiers', symbol: 'AAVAS', exchange: 'NSE', ticker: 'AAVAS.NS', currency: '₹' },
  { name: 'Home First Finance', symbol: 'HOMEFIRST', exchange: 'NSE', ticker: 'HOMEFIRST.NS', currency: '₹' },

  // Regional Banks & Midcap Financials
  { name: 'AU Small Finance', symbol: 'AUBANK', exchange: 'NSE', ticker: 'AUBANK.NS', currency: '₹' },
  { name: 'City Union Bank', symbol: 'CUB', exchange: 'NSE', ticker: 'CUB.NS', currency: '₹' },
  { name: 'Karur Vysya Bank', symbol: 'KARURVYSYA', exchange: 'NSE', ticker: 'KARURVYSYA.NS', currency: '₹' },
  { name: 'Bank of India', symbol: 'BANKINDIA', exchange: 'NSE', ticker: 'BANKINDIA.NS', currency: '₹' },
  { name: 'Indian Bank', symbol: 'INDIANB', exchange: 'NSE', ticker: 'INDIANB.NS', currency: '₹' },
  { name: 'Bank of Maharashtra', symbol: 'MAHABANK', exchange: 'NSE', ticker: 'MAHABANK.NS', currency: '₹' },
  { name: 'Central Bank', symbol: 'CENTRALBK', exchange: 'NSE', ticker: 'CENTRALBK.NS', currency: '₹' },
  { name: 'UCO Bank', symbol: 'UCOBANK', exchange: 'NSE', ticker: 'UCOBANK.NS', currency: '₹' },
  { name: 'Indian Overseas Bank', symbol: 'IOB', exchange: 'NSE', ticker: 'IOB.NS', currency: '₹' },
  { name: 'L&T Finance', symbol: 'LTF', exchange: 'NSE', ticker: 'LTF.NS', currency: '₹' },

  // Real Estate & Construction
  { name: 'DLF', symbol: 'DLF', exchange: 'NSE', ticker: 'DLF.NS', currency: '₹' },
  { name: 'Macrotech Dev (Lodha)', symbol: 'LODHA', exchange: 'NSE', ticker: 'LODHA.NS', currency: '₹' },
  { name: 'Godrej Properties', symbol: 'GODREJPROP', exchange: 'NSE', ticker: 'GODREJPROP.NS', currency: '₹' },
  { name: 'Oberoi Realty', symbol: 'OBEROIRLTY', exchange: 'NSE', ticker: 'OBEROIRLTY.NS', currency: '₹' },
  { name: 'Prestige Estates', symbol: 'PRESTIGE', exchange: 'NSE', ticker: 'PRESTIGE.NS', currency: '₹' },
  { name: 'Sobha', symbol: 'SOBHA', exchange: 'NSE', ticker: 'SOBHA.NS', currency: '₹' },
  { name: 'Brigade Enterprises', symbol: 'BRIGADE', exchange: 'NSE', ticker: 'BRIGADE.NS', currency: '₹' },
  { name: 'Puravankara', symbol: 'PURVA', exchange: 'NSE', ticker: 'PURVA.NS', currency: '₹' },
  { name: 'Sunteck Realty', symbol: 'SUNTECK', exchange: 'NSE', ticker: 'SUNTECK.NS', currency: '₹' },
  { name: 'Phoenix Mills', symbol: 'PHOENIXLTD', exchange: 'NSE', ticker: 'PHOENIXLTD.NS', currency: '₹' },

  // Consumer Durables, Electronics & Footwear
  { name: 'Dixon Technologies', symbol: 'DIXON', exchange: 'NSE', ticker: 'DIXON.NS', currency: '₹' },
  { name: 'Amber Enterprises', symbol: 'AMBER', exchange: 'NSE', ticker: 'AMBER.NS', currency: '₹' },
  { name: 'Voltas', symbol: 'VOLTAS', exchange: 'NSE', ticker: 'VOLTAS.NS', currency: '₹' },
  { name: 'Blue Star', symbol: 'BLUESTARCO', exchange: 'NSE', ticker: 'BLUESTARCO.NS', currency: '₹' },
  { name: 'Whirlpool India', symbol: 'WHIRLPOOL', exchange: 'NSE', ticker: 'WHIRLPOOL.NS', currency: '₹' },
  { name: 'V-Guard', symbol: 'VGUARD', exchange: 'NSE', ticker: 'VGUARD.NS', currency: '₹' },
  { name: 'Symphony', symbol: 'SYMPHONY', exchange: 'NSE', ticker: 'SYMPHONY.NS', currency: '₹' },
  { name: 'TTK Prestige', symbol: 'TTKPRESTIG', exchange: 'NSE', ticker: 'TTKPRESTIG.NS', currency: '₹' },
  { name: 'Bata India', symbol: 'BATAINDIA', exchange: 'NSE', ticker: 'BATAINDIA.NS', currency: '₹' },
  { name: 'Metro Brands', symbol: 'METROBRAND', exchange: 'NSE', ticker: 'METROBRAND.NS', currency: '₹' },
  { name: 'Relaxo Footwears', symbol: 'RELAXO', exchange: 'NSE', ticker: 'RELAXO.NS', currency: '₹' },
  { name: 'Campus Activewear', symbol: 'CAMPUS', exchange: 'NSE', ticker: 'CAMPUS.NS', currency: '₹' },
  { name: 'Kajaria Ceramics', symbol: 'KAJARIACER', exchange: 'NSE', ticker: 'KAJARIACER.NS', currency: '₹' },
  { name: 'Cera Sanitaryware', symbol: 'CERA', exchange: 'NSE', ticker: 'CERA.NS', currency: '₹' },
  { name: 'Century Plyboards', symbol: 'CENTURYPLY', exchange: 'NSE', ticker: 'CENTURYPLY.NS', currency: '₹' },

  // Textiles, Apparels & Retail
  { name: 'Page Industries', symbol: 'PAGEIND', exchange: 'NSE', ticker: 'PAGEIND.NS', currency: '₹' },
  { name: 'KPR Mill', symbol: 'KPRMILL', exchange: 'NSE', ticker: 'KPRMILL.NS', currency: '₹' },
  { name: 'Trident', symbol: 'TRIDENT', exchange: 'NSE', ticker: 'TRIDENT.NS', currency: '₹' },
  { name: 'Welspun Living', symbol: 'WELSPUNLIV', exchange: 'NSE', ticker: 'WELSPUNLIV.NS', currency: '₹' },
  { name: 'Vardhman Textiles', symbol: 'VTL', exchange: 'NSE', ticker: 'VTL.NS', currency: '₹' },
  { name: 'Raymond', symbol: 'RAYMOND', exchange: 'NSE', ticker: 'RAYMOND.NS', currency: '₹' },
  { name: 'Arvind', symbol: 'ARVIND', exchange: 'NSE', ticker: 'ARVIND.NS', currency: '₹' },
  { name: 'Shoppers Stop', symbol: 'SHOPPERS', exchange: 'NSE', ticker: 'SHOPPERS.NS', currency: '₹' },
  { name: 'Nykaa', symbol: 'NYKAA', exchange: 'NSE', ticker: 'NYKAA.NS', currency: '₹' },
  { name: 'Bikaji Foods', symbol: 'BIKAJI', exchange: 'NSE', ticker: 'BIKAJI.NS', currency: '₹' },

  // Media, Entertainment & Hospitality
  { name: 'Zee Entertainment', symbol: 'ZEEL', exchange: 'NSE', ticker: 'ZEEL.NS', currency: '₹' },
  { name: 'Sun TV', symbol: 'SUNTV', exchange: 'NSE', ticker: 'SUNTV.NS', currency: '₹' },
  { name: 'PVR INOX', symbol: 'PVRINOX', exchange: 'NSE', ticker: 'PVRINOX.NS', currency: '₹' },
  { name: 'Saregama India', symbol: 'SAREGAMA', exchange: 'NSE', ticker: 'SAREGAMA.NS', currency: '₹' },
  { name: 'Network18', symbol: 'NETWORK18', exchange: 'NSE', ticker: 'NETWORK18.NS', currency: '₹' },
  { name: 'Indian Hotels', symbol: 'INDHOTEL', exchange: 'NSE', ticker: 'INDHOTEL.NS', currency: '₹' },
  { name: 'Chalet Hotels', symbol: 'CHALET', exchange: 'NSE', ticker: 'CHALET.NS', currency: '₹' },
  { name: 'Lemon Tree Hotels', symbol: 'LEMONTREE', exchange: 'NSE', ticker: 'LEMONTREE.NS', currency: '₹' },
  { name: 'EIH Ltd', symbol: 'EIHOTEL', exchange: 'NSE', ticker: 'EIHOTEL.NS', currency: '₹' },

  // Midcap Pharma & Healthcare
  { name: 'Abbott India', symbol: 'ABBOTINDIA', exchange: 'NSE', ticker: 'ABBOTINDIA.NS', currency: '₹' },
  { name: 'Alkem Laboratories', symbol: 'ALKEM', exchange: 'NSE', ticker: 'ALKEM.NS', currency: '₹' },
  { name: 'Ajanta Pharma', symbol: 'AJANTPHARM', exchange: 'NSE', ticker: 'AJANTPHARM.NS', currency: '₹' },
  { name: 'IPCA Labs', symbol: 'IPCALAB', exchange: 'NSE', ticker: 'IPCALAB.NS', currency: '₹' },
  { name: 'JB Chemicals', symbol: 'JBCHEPHARM', exchange: 'NSE', ticker: 'JBCHEPHARM.NS', currency: '₹' },
  { name: 'Natco Pharma', symbol: 'NATCOPHARM', exchange: 'NSE', ticker: 'NATCOPHARM.NS', currency: '₹' },
  { name: 'Sanofi India', symbol: 'SANOFI', exchange: 'NSE', ticker: 'SANOFI.NS', currency: '₹' },
  { name: 'Pfizer India', symbol: 'PFIZER', exchange: 'NSE', ticker: 'PFIZER.NS', currency: '₹' },
  { name: 'GlaxoSmithKline', symbol: 'GLAXO', exchange: 'NSE', ticker: 'GLAXO.NS', currency: '₹' },
  { name: 'AstraZeneca India', symbol: 'ASTRAZEN', exchange: 'NSE', ticker: 'ASTRAZEN.NS', currency: '₹' },
  { name: 'Metropolis Healthcare', symbol: 'METROPOLIS', exchange: 'NSE', ticker: 'METROPOLIS.NS', currency: '₹' },
  { name: 'Dr. Lal PathLabs', symbol: 'LALPATHLAB', exchange: 'NSE', ticker: 'LALPATHLAB.NS', currency: '₹' },

  // Capital Goods, Engineering & Manufacturing
  { name: 'Siemens India', symbol: 'SIEMENS', exchange: 'NSE', ticker: 'SIEMENS.NS', currency: '₹' },
  { name: 'ABB India', symbol: 'ABB', exchange: 'NSE', ticker: 'ABB.NS', currency: '₹' },
  { name: 'CG Power', symbol: 'CGPOWER', exchange: 'NSE', ticker: 'CGPOWER.NS', currency: '₹' },
  { name: 'KEC International', symbol: 'KEC', exchange: 'NSE', ticker: 'KEC.NS', currency: '₹' },
  { name: 'Kalpataru Projects', symbol: 'KPIL', exchange: 'NSE', ticker: 'KPIL.NS', currency: '₹' },
  { name: 'Thermax', symbol: 'THERMAX', exchange: 'NSE', ticker: 'THERMAX.NS', currency: '₹' },
  { name: 'Honeywell Auto', symbol: 'HONAUT', exchange: 'NSE', ticker: 'HONAUT.NS', currency: '₹' },
  { name: 'Triveni Turbine', symbol: 'TRITURBINE', exchange: 'NSE', ticker: 'TRITURBINE.NS', currency: '₹' },
  { name: 'SKF India', symbol: 'SKFINDIA', exchange: 'NSE', ticker: 'SKFINDIA.NS', currency: '₹' },
  { name: 'Timken India', symbol: 'TIMKEN', exchange: 'NSE', ticker: 'TIMKEN.NS', currency: '₹' },
  
  // Fertilizers & Midcap Chemicals
  { name: 'Chambal Fertilisers', symbol: 'CHAMBLFERT', exchange: 'NSE', ticker: 'CHAMBLFERT.NS', currency: '₹' },
  { name: 'GNFC', symbol: 'GNFC', exchange: 'NSE', ticker: 'GNFC.NS', currency: '₹' },
  { name: 'GSFC', symbol: 'GSFC', exchange: 'NSE', ticker: 'GSFC.NS', currency: '₹' },
  { name: 'RCF', symbol: 'RCF', exchange: 'NSE', ticker: 'RCF.NS', currency: '₹' },
  { name: 'FACT', symbol: 'FACT', exchange: 'NSE', ticker: 'FACT.NS', currency: '₹' },
  { name: 'Atul Ltd', symbol: 'ATUL', exchange: 'NSE', ticker: 'ATUL.NS', currency: '₹' },
  { name: 'Gujarat Fluorochem', symbol: 'FLUOROCHEM', exchange: 'NSE', ticker: 'FLUOROCHEM.NS', currency: '₹' },
  { name: 'Castrol India', symbol: 'CASTROLIND', exchange: 'NSE', ticker: 'CASTROLIND.NS', currency: '₹' },
  // frontend/app/stocks.ts
// BSE BATCH 1 (125 Stocks)

  // Financials & Banks (BSE)
  { name: 'HDFC Bank', symbol: 'HDFCBANK', exchange: 'BSE', ticker: 'HDFCBANK.BO', currency: '₹' },
  { name: 'ICICI Bank', symbol: 'ICICIBANK', exchange: 'BSE', ticker: 'ICICIBANK.BO', currency: '₹' },
  { name: 'State Bank of India', symbol: 'SBIN', exchange: 'BSE', ticker: 'SBIN.BO', currency: '₹' },
  { name: 'Axis Bank', symbol: 'AXISBANK', exchange: 'BSE', ticker: 'AXISBANK.BO', currency: '₹' },
  { name: 'Kotak Mahindra', symbol: 'KOTAKBANK', exchange: 'BSE', ticker: 'KOTAKBANK.BO', currency: '₹' },
  { name: 'IndusInd Bank', symbol: 'INDUSINDBK', exchange: 'BSE', ticker: 'INDUSINDBK.BO', currency: '₹' },
  { name: 'Bank of Baroda', symbol: 'BANKBARODA', exchange: 'BSE', ticker: 'BANKBARODA.BO', currency: '₹' },
  { name: 'Punjab National Bank', symbol: 'PNB', exchange: 'BSE', ticker: 'PNB.BO', currency: '₹' },
  { name: 'Canara Bank', symbol: 'CANBK', exchange: 'BSE', ticker: 'CANBK.BO', currency: '₹' },
  { name: 'IDFC First Bank', symbol: 'IDFCFIRSTB', exchange: 'BSE', ticker: 'IDFCFIRSTB.BO', currency: '₹' },
  { name: 'Federal Bank', symbol: 'FEDERALBNK', exchange: 'BSE', ticker: 'FEDERALBNK.BO', currency: '₹' },
  { name: 'Bandhan Bank', symbol: 'BANDHANBNK', exchange: 'BSE', ticker: 'BANDHANBNK.BO', currency: '₹' },
  { name: 'Bajaj Finance', symbol: 'BAJFINANCE', exchange: 'BSE', ticker: 'BAJFINANCE.BO', currency: '₹' },
  { name: 'Bajaj Finserv', symbol: 'BAJAJFINSV', exchange: 'BSE', ticker: 'BAJAJFINSV.BO', currency: '₹' },
  { name: 'Cholamandalam Inv', symbol: 'CHOLAFIN', exchange: 'BSE', ticker: 'CHOLAFIN.BO', currency: '₹' },
  { name: 'Shriram Finance', symbol: 'SHRIRAMFIN', exchange: 'BSE', ticker: 'SHRIRAMFIN.BO', currency: '₹' },
  { name: 'Muthoot Finance', symbol: 'MUTHOOTFIN', exchange: 'BSE', ticker: 'MUTHOOTFIN.BO', currency: '₹' },
  { name: 'PFC', symbol: 'PFC', exchange: 'BSE', ticker: 'PFC.BO', currency: '₹' },
  { name: 'REC Ltd', symbol: 'RECLTD', exchange: 'BSE', ticker: 'RECLTD.BO', currency: '₹' },
  { name: 'SBI Cards', symbol: 'SBICARD', exchange: 'BSE', ticker: 'SBICARD.BO', currency: '₹' },

  // IT & Tech (BSE)
  { name: 'TCS', symbol: 'TCS', exchange: 'BSE', ticker: 'TCS.BO', currency: '₹' },
  { name: 'Infosys', symbol: 'INFY', exchange: 'BSE', ticker: 'INFY.BO', currency: '₹' },
  { name: 'HCL Technologies', symbol: 'HCLTECH', exchange: 'BSE', ticker: 'HCLTECH.BO', currency: '₹' },
  { name: 'Wipro', symbol: 'WIPRO', exchange: 'BSE', ticker: 'WIPRO.BO', currency: '₹' },
  { name: 'Tech Mahindra', symbol: 'TECHM', exchange: 'BSE', ticker: 'TECHM.BO', currency: '₹' },
  { name: 'LTIMindtree', symbol: 'LTIM', exchange: 'BSE', ticker: 'LTIM.BO', currency: '₹' },
  { name: 'Coforge', symbol: 'COFORGE', exchange: 'BSE', ticker: 'COFORGE.BO', currency: '₹' },
  { name: 'Persistent Systems', symbol: 'PERSISTENT', exchange: 'BSE', ticker: 'PERSISTENT.BO', currency: '₹' },
  { name: 'Mphasis', symbol: 'MPHASIS', exchange: 'BSE', ticker: 'MPHASIS.BO', currency: '₹' },
  { name: 'L&T Technology Services', symbol: 'LTTS', exchange: 'BSE', ticker: 'LTTS.BO', currency: '₹' },

  // Auto & Auto Components (BSE)
  { name: 'Tata Motors', symbol: 'TATAMOTORS', exchange: 'BSE', ticker: 'TATAMOTORS.BO', currency: '₹' },
  { name: 'Maruti Suzuki', symbol: 'MARUTI', exchange: 'BSE', ticker: 'MARUTI.BO', currency: '₹' },
  { name: 'Mahindra & Mahindra', symbol: 'M&M', exchange: 'BSE', ticker: 'M&M.BO', currency: '₹' },
  { name: 'Bajaj Auto', symbol: 'BAJAJ-AUTO', exchange: 'BSE', ticker: 'BAJAJ-AUTO.BO', currency: '₹' },
  { name: 'Eicher Motors', symbol: 'EICHERMOT', exchange: 'BSE', ticker: 'EICHERMOT.BO', currency: '₹' },
  { name: 'Hero MotoCorp', symbol: 'HEROMOTOCO', exchange: 'BSE', ticker: 'HEROMOTOCO.BO', currency: '₹' },
  { name: 'TVS Motor', symbol: 'TVSMOTOR', exchange: 'BSE', ticker: 'TVSMOTOR.BO', currency: '₹' },
  { name: 'Ashok Leyland', symbol: 'ASHOKLEY', exchange: 'BSE', ticker: 'ASHOKLEY.BO', currency: '₹' },
  { name: 'Escorts Kubota', symbol: 'ESCORTS', exchange: 'BSE', ticker: 'ESCORTS.BO', currency: '₹' },
  { name: 'Tube Investments', symbol: 'TIINDIA', exchange: 'BSE', ticker: 'TIINDIA.BO', currency: '₹' },
  { name: 'Bosch Ltd', symbol: 'BOSCHLTD', exchange: 'BSE', ticker: 'BOSCHLTD.BO', currency: '₹' },
  { name: 'MRF', symbol: 'MRF', exchange: 'BSE', ticker: 'MRF.BO', currency: '₹' },
  { name: 'Balkrishna Industries', symbol: 'BALKRISIND', exchange: 'BSE', ticker: 'BALKRISIND.BO', currency: '₹' },
  { name: 'Samvardhana Motherson', symbol: 'MOTHERSON', exchange: 'BSE', ticker: 'MOTHERSON.BO', currency: '₹' },
  { name: 'Cummins India', symbol: 'CUMMINSIND', exchange: 'BSE', ticker: 'CUMMINSIND.BO', currency: '₹' },

  // FMCG & Consumer Goods (BSE)
  { name: 'ITC Ltd', symbol: 'ITC', exchange: 'BSE', ticker: 'ITC.BO', currency: '₹' },
  { name: 'Hindustan Unilever', symbol: 'HINDUNILVR', exchange: 'BSE', ticker: 'HINDUNILVR.BO', currency: '₹' },
  { name: 'Nestle India', symbol: 'NESTLEIND', exchange: 'BSE', ticker: 'NESTLEIND.BO', currency: '₹' },
  { name: 'Britannia', symbol: 'BRITANNIA', exchange: 'BSE', ticker: 'BRITANNIA.BO', currency: '₹' },
  { name: 'Tata Consumer', symbol: 'TATACONSUM', exchange: 'BSE', ticker: 'TATACONSUM.BO', currency: '₹' },
  { name: 'Dabur India', symbol: 'DABUR', exchange: 'BSE', ticker: 'DABUR.BO', currency: '₹' },
  { name: 'Godrej Consumer', symbol: 'GODREJCP', exchange: 'BSE', ticker: 'GODREJCP.BO', currency: '₹' },
  { name: 'Marico', symbol: 'MARICO', exchange: 'BSE', ticker: 'MARICO.BO', currency: '₹' },
  { name: 'Colgate Palmolive', symbol: 'COLPAL', exchange: 'BSE', ticker: 'COLPAL.BO', currency: '₹' },
  { name: 'Varun Beverages', symbol: 'VBL', exchange: 'BSE', ticker: 'VBL.BO', currency: '₹' },
  { name: 'United Breweries', symbol: 'UBL', exchange: 'BSE', ticker: 'UBL.BO', currency: '₹' },
  { name: 'United Spirits', symbol: 'MCDOWELL-N', exchange: 'BSE', ticker: 'MCDOWELL-N.BO', currency: '₹' },
  { name: 'Balrampur Chini', symbol: 'BALRAMCHIN', exchange: 'BSE', ticker: 'BALRAMCHIN.BO', currency: '₹' },
  { name: 'Radico Khaitan', symbol: 'RADICO', exchange: 'BSE', ticker: 'RADICO.BO', currency: '₹' },
  { name: 'Emami', symbol: 'EMAMILTD', exchange: 'BSE', ticker: 'EMAMILTD.BO', currency: '₹' },

  // Pharma & Healthcare (BSE)
  { name: 'Sun Pharma', symbol: 'SUNPHARMA', exchange: 'BSE', ticker: 'SUNPHARMA.BO', currency: '₹' },
  { name: 'Dr. Reddys Labs', symbol: 'DRREDDY', exchange: 'BSE', ticker: 'DRREDDY.BO', currency: '₹' },
  { name: 'Cipla', symbol: 'CIPLA', exchange: 'BSE', ticker: 'CIPLA.BO', currency: '₹' },
  { name: 'Divis Labs', symbol: 'DIVISLAB', exchange: 'BSE', ticker: 'DIVISLAB.BO', currency: '₹' },
  { name: 'Apollo Hospitals', symbol: 'APOLLOHOSP', exchange: 'BSE', ticker: 'APOLLOHOSP.BO', currency: '₹' },
  { name: 'Lupin', symbol: 'LUPIN', exchange: 'BSE', ticker: 'LUPIN.BO', currency: '₹' },
  { name: 'Torrent Pharma', symbol: 'TORNTPHARM', exchange: 'BSE', ticker: 'TORNTPHARM.BO', currency: '₹' },
  { name: 'Zydus Lifesciences', symbol: 'ZYDUSLIFE', exchange: 'BSE', ticker: 'ZYDUSLIFE.BO', currency: '₹' },
  { name: 'Aurobindo Pharma', symbol: 'AUROPHARMA', exchange: 'BSE', ticker: 'AUROPHARMA.BO', currency: '₹' },
  { name: 'Biocon', symbol: 'BIOCON', exchange: 'BSE', ticker: 'BIOCON.BO', currency: '₹' },
  { name: 'Syngene', symbol: 'SYNGENE', exchange: 'BSE', ticker: 'SYNGENE.BO', currency: '₹' },
  { name: 'Max Healthcare', symbol: 'MAXHEALTH', exchange: 'BSE', ticker: 'MAXHEALTH.BO', currency: '₹' },
  { name: 'Glenmark', symbol: 'GLENMARK', exchange: 'BSE', ticker: 'GLENMARK.BO', currency: '₹' },
  { name: 'Laurus Labs', symbol: 'LAURUSLABS', exchange: 'BSE', ticker: 'LAURUSLABS.BO', currency: '₹' },
  { name: 'Granules India', symbol: 'GRANULES', exchange: 'BSE', ticker: 'GRANULES.BO', currency: '₹' },

  // Energy, Oil & Gas (BSE)
  { name: 'Reliance Industries', symbol: 'RELIANCE', exchange: 'BSE', ticker: 'RELIANCE.BO', currency: '₹' },
  { name: 'ONGC', symbol: 'ONGC', exchange: 'BSE', ticker: 'ONGC.BO', currency: '₹' },
  { name: 'NTPC', symbol: 'NTPC', exchange: 'BSE', ticker: 'NTPC.BO', currency: '₹' },
  { name: 'Power Grid', symbol: 'POWERGRID', exchange: 'BSE', ticker: 'POWERGRID.BO', currency: '₹' },
  { name: 'Coal India', symbol: 'COALINDIA', exchange: 'BSE', ticker: 'COALINDIA.BO', currency: '₹' },
  { name: 'Tata Power', symbol: 'TATAPOWER', exchange: 'BSE', ticker: 'TATAPOWER.BO', currency: '₹' },
  { name: 'Indraprastha Gas', symbol: 'IGL', exchange: 'BSE', ticker: 'IGL.BO', currency: '₹' },
  { name: 'Mahanagar Gas', symbol: 'MGL', exchange: 'BSE', ticker: 'MGL.BO', currency: '₹' },
  { name: 'GAIL', symbol: 'GAIL', exchange: 'BSE', ticker: 'GAIL.BO', currency: '₹' },
  { name: 'BPCL', symbol: 'BPCL', exchange: 'BSE', ticker: 'BPCL.BO', currency: '₹' },
  { name: 'HPCL', symbol: 'HINDPETRO', exchange: 'BSE', ticker: 'HINDPETRO.BO', currency: '₹' },
  { name: 'IOCL', symbol: 'IOC', exchange: 'BSE', ticker: 'IOC.BO', currency: '₹' },

  // Metals & Mining (BSE)
  { name: 'Tata Steel', symbol: 'TATASTEEL', exchange: 'BSE', ticker: 'TATASTEEL.BO', currency: '₹' },
  { name: 'JSW Steel', symbol: 'JSWSTEEL', exchange: 'BSE', ticker: 'JSWSTEEL.BO', currency: '₹' },
  { name: 'Hindalco', symbol: 'HINDALCO', exchange: 'BSE', ticker: 'HINDALCO.BO', currency: '₹' },
  { name: 'Vedanta', symbol: 'VEDL', exchange: 'BSE', ticker: 'VEDL.BO', currency: '₹' },
  { name: 'NMDC', symbol: 'NMDC', exchange: 'BSE', ticker: 'NMDC.BO', currency: '₹' },
  { name: 'SAIL', symbol: 'SAIL', exchange: 'BSE', ticker: 'SAIL.BO', currency: '₹' },
  { name: 'Jindal Steel', symbol: 'JINDALSTEL', exchange: 'BSE', ticker: 'JINDALSTEL.BO', currency: '₹' },
  { name: 'NALCO', symbol: 'NATIONALUM', exchange: 'BSE', ticker: 'NATIONALUM.BO', currency: '₹' },
  { name: 'Hindustan Zinc', symbol: 'HZL', exchange: 'BSE', ticker: 'HZL.BO', currency: '₹' },
  { name: 'APL Apollo Tubes', symbol: 'APLAPOLLO', exchange: 'BSE', ticker: 'APLAPOLLO.BO', currency: '₹' },

  // Infrastructure, Cement & Chemicals (BSE)
  { name: 'Larsen & Toubro', symbol: 'LT', exchange: 'BSE', ticker: 'LT.BO', currency: '₹' },
  { name: 'UltraTech Cement', symbol: 'ULTRACEMCO', exchange: 'BSE', ticker: 'ULTRACEMCO.BO', currency: '₹' },
  { name: 'Grasim', symbol: 'GRASIM', exchange: 'BSE', ticker: 'GRASIM.BO', currency: '₹' },
  { name: 'Ambuja Cements', symbol: 'AMBUJACEM', exchange: 'BSE', ticker: 'AMBUJACEM.BO', currency: '₹' },
  { name: 'Shree Cement', symbol: 'SHREECEM', exchange: 'BSE', ticker: 'SHREECEM.BO', currency: '₹' },
  { name: 'ACC', symbol: 'ACC', exchange: 'BSE', ticker: 'ACC.BO', currency: '₹' },
  { name: 'Dalmia Bharat', symbol: 'DALBHARAT', exchange: 'BSE', ticker: 'DALBHARAT.BO', currency: '₹' },
  { name: 'Ramco Cements', symbol: 'RAMCOCEM', exchange: 'BSE', ticker: 'RAMCOCEM.BO', currency: '₹' },
  // frontend/app/stocks.ts
// BSE BATCH 2 (125 Stocks)

  // Midcap IT & Telecom (BSE)
  { name: 'Tata Communications', symbol: 'TATACOMM', exchange: 'BSE', ticker: 'TATACOMM.BO', currency: '₹' },
  { name: 'Tata Elxsi', symbol: 'TATAELXSI', exchange: 'BSE', ticker: 'TATAELXSI.BO', currency: '₹' },
  { name: 'KPIT Technologies', symbol: 'KPITTECH', exchange: 'BSE', ticker: 'KPITTECH.BO', currency: '₹' },
  { name: 'Mphasis', symbol: 'MPHASIS', exchange: 'BSE', ticker: 'MPHASIS.BO', currency: '₹' },
  { name: 'Birlasoft', symbol: 'BSOFT', exchange: 'BSE', ticker: 'BSOFT.BO', currency: '₹' },
  { name: 'Cyient', symbol: 'CYIENT', exchange: 'BSE', ticker: 'CYIENT.BO', currency: '₹' },
  { name: 'Zensar Tech', symbol: 'ZENSARTECH', exchange: 'BSE', ticker: 'ZENSARTECH.BO', currency: '₹' },
  { name: 'Sonata Software', symbol: 'SONATSOFTW', exchange: 'BSE', ticker: 'SONATSOFTW.BO', currency: '₹' },
  { name: 'Vodafone Idea', symbol: 'IDEA', exchange: 'BSE', ticker: 'IDEA.BO', currency: '₹' },
  { name: 'Indus Towers', symbol: 'INDUSTOWER', exchange: 'BSE', ticker: 'INDUSTOWER.BO', currency: '₹' },

  // Defense, Aerospace & Shipyards (BSE)
  { name: 'Hindustan Aeronautics', symbol: 'HAL', exchange: 'BSE', ticker: 'HAL.BO', currency: '₹' },
  { name: 'Bharat Electronics', symbol: 'BEL', exchange: 'BSE', ticker: 'BEL.BO', currency: '₹' },
  { name: 'Mazagon Dock', symbol: 'MAZDOCK', exchange: 'BSE', ticker: 'MAZDOCK.BO', currency: '₹' },
  { name: 'Cochin Shipyard', symbol: 'COCHINSHIP', exchange: 'BSE', ticker: 'COCHINSHIP.BO', currency: '₹' },
  { name: 'Garden Reach', symbol: 'GRSE', exchange: 'BSE', ticker: 'GRSE.BO', currency: '₹' },
  { name: 'Bharat Dynamics', symbol: 'BDL', exchange: 'BSE', ticker: 'BDL.BO', currency: '₹' },
  { name: 'BEML', symbol: 'BEML', exchange: 'BSE', ticker: 'BEML.BO', currency: '₹' },
  { name: 'MTAR Technologies', symbol: 'MTARTECH', exchange: 'BSE', ticker: 'MTARTECH.BO', currency: '₹' },
  { name: 'Data Patterns', symbol: 'DATAPATTNS', exchange: 'BSE', ticker: 'DATAPATTNS.BO', currency: '₹' },

  // Asset Management, Brokers & Exchanges (BSE)
  { name: 'BSE Ltd', symbol: 'BSE', exchange: 'BSE', ticker: 'BSE.BO', currency: '₹' },
  { name: 'MCX India', symbol: 'MCX', exchange: 'BSE', ticker: 'MCX.BO', currency: '₹' },
  { name: 'CDSL', symbol: 'CDSL', exchange: 'BSE', ticker: 'CDSL.BO', currency: '₹' },
  { name: 'CAMS', symbol: 'CAMS', exchange: 'BSE', ticker: 'CAMS.BO', currency: '₹' },
  { name: 'Angel One', symbol: 'ANGELONE', exchange: 'BSE', ticker: 'ANGELONE.BO', currency: '₹' },
  { name: 'HDFC AMC', symbol: 'HDFCAMC', exchange: 'BSE', ticker: 'HDFCAMC.BO', currency: '₹' },
  { name: 'Nippon Life India', symbol: 'NAM-INDIA', exchange: 'BSE', ticker: 'NAM-INDIA.BO', currency: '₹' },
  { name: 'UTI AMC', symbol: 'UTIAMC', exchange: 'BSE', ticker: 'UTIAMC.BO', currency: '₹' },
  { name: 'Aditya Birla Capital', symbol: 'ABCAPITAL', exchange: 'BSE', ticker: 'ABCAPITAL.BO', currency: '₹' },
  { name: 'ICICI Securities', symbol: 'ISEC', exchange: 'BSE', ticker: 'ISEC.BO', currency: '₹' },

  // Insurance & Housing Finance (BSE)
  { name: 'ICICI Lombard', symbol: 'ICICIGI', exchange: 'BSE', ticker: 'ICICIGI.BO', currency: '₹' },
  { name: 'Star Health', symbol: 'STARHEALTH', exchange: 'BSE', ticker: 'STARHEALTH.BO', currency: '₹' },
  { name: 'General Insurance', symbol: 'GICRE', exchange: 'BSE', ticker: 'GICRE.BO', currency: '₹' },
  { name: 'LIC Housing Finance', symbol: 'LICHSGFIN', exchange: 'BSE', ticker: 'LICHSGFIN.BO', currency: '₹' },
  { name: 'PNB Housing', symbol: 'PNBHOUSING', exchange: 'BSE', ticker: 'PNBHOUSING.BO', currency: '₹' },
  { name: 'Can Fin Homes', symbol: 'CANFINHOME', exchange: 'BSE', ticker: 'CANFINHOME.BO', currency: '₹' },
  { name: 'Aavas Financiers', symbol: 'AAVAS', exchange: 'BSE', ticker: 'AAVAS.BO', currency: '₹' },
  { name: 'Home First Finance', symbol: 'HOMEFIRST', exchange: 'BSE', ticker: 'HOMEFIRST.BO', currency: '₹' },

  // Regional Banks & Midcap Financials (BSE)
  { name: 'AU Small Finance', symbol: 'AUBANK', exchange: 'BSE', ticker: 'AUBANK.BO', currency: '₹' },
  { name: 'City Union Bank', symbol: 'CUB', exchange: 'BSE', ticker: 'CUB.BO', currency: '₹' },
  { name: 'Karur Vysya Bank', symbol: 'KARURVYSYA', exchange: 'BSE', ticker: 'KARURVYSYA.BO', currency: '₹' },
  { name: 'Bank of India', symbol: 'BANKINDIA', exchange: 'BSE', ticker: 'BANKINDIA.BO', currency: '₹' },
  { name: 'Indian Bank', symbol: 'INDIANB', exchange: 'BSE', ticker: 'INDIANB.BO', currency: '₹' },
  { name: 'Bank of Maharashtra', symbol: 'MAHABANK', exchange: 'BSE', ticker: 'MAHABANK.BO', currency: '₹' },
  { name: 'Central Bank', symbol: 'CENTRALBK', exchange: 'BSE', ticker: 'CENTRALBK.BO', currency: '₹' },
  { name: 'UCO Bank', symbol: 'UCOBANK', exchange: 'BSE', ticker: 'UCOBANK.BO', currency: '₹' },
  { name: 'Indian Overseas Bank', symbol: 'IOB', exchange: 'BSE', ticker: 'IOB.BO', currency: '₹' },
  { name: 'L&T Finance', symbol: 'LTF', exchange: 'BSE', ticker: 'LTF.BO', currency: '₹' },

  // Real Estate & Construction (BSE)
  { name: 'DLF', symbol: 'DLF', exchange: 'BSE', ticker: 'DLF.BO', currency: '₹' },
  { name: 'Macrotech Dev (Lodha)', symbol: 'LODHA', exchange: 'BSE', ticker: 'LODHA.BO', currency: '₹' },
  { name: 'Godrej Properties', symbol: 'GODREJPROP', exchange: 'BSE', ticker: 'GODREJPROP.BO', currency: '₹' },
  { name: 'Oberoi Realty', symbol: 'OBEROIRLTY', exchange: 'BSE', ticker: 'OBEROIRLTY.BO', currency: '₹' },
  { name: 'Prestige Estates', symbol: 'PRESTIGE', exchange: 'BSE', ticker: 'PRESTIGE.BO', currency: '₹' },
  { name: 'Sobha', symbol: 'SOBHA', exchange: 'BSE', ticker: 'SOBHA.BO', currency: '₹' },
  { name: 'Brigade Enterprises', symbol: 'BRIGADE', exchange: 'BSE', ticker: 'BRIGADE.BO', currency: '₹' },
  { name: 'Puravankara', symbol: 'PURVA', exchange: 'BSE', ticker: 'PURVA.BO', currency: '₹' },
  { name: 'Sunteck Realty', symbol: 'SUNTECK', exchange: 'BSE', ticker: 'SUNTECK.BO', currency: '₹' },
  { name: 'Phoenix Mills', symbol: 'PHOENIXLTD', exchange: 'BSE', ticker: 'PHOENIXLTD.BO', currency: '₹' },

  // Consumer Durables, Electronics & Footwear (BSE)
  { name: 'Dixon Technologies', symbol: 'DIXON', exchange: 'BSE', ticker: 'DIXON.BO', currency: '₹' },
  { name: 'Amber Enterprises', symbol: 'AMBER', exchange: 'BSE', ticker: 'AMBER.BO', currency: '₹' },
  { name: 'Voltas', symbol: 'VOLTAS', exchange: 'BSE', ticker: 'VOLTAS.BO', currency: '₹' },
  { name: 'Blue Star', symbol: 'BLUESTARCO', exchange: 'BSE', ticker: 'BLUESTARCO.BO', currency: '₹' },
  { name: 'Whirlpool India', symbol: 'WHIRLPOOL', exchange: 'BSE', ticker: 'WHIRLPOOL.BO', currency: '₹' },
  { name: 'V-Guard', symbol: 'VGUARD', exchange: 'BSE', ticker: 'VGUARD.BO', currency: '₹' },
  { name: 'Symphony', symbol: 'SYMPHONY', exchange: 'BSE', ticker: 'SYMPHONY.BO', currency: '₹' },
  { name: 'TTK Prestige', symbol: 'TTKPRESTIG', exchange: 'BSE', ticker: 'TTKPRESTIG.BO', currency: '₹' },
  { name: 'Bata India', symbol: 'BATAINDIA', exchange: 'BSE', ticker: 'BATAINDIA.BO', currency: '₹' },
  { name: 'Metro Brands', symbol: 'METROBRAND', exchange: 'BSE', ticker: 'METROBRAND.BO', currency: '₹' },
  { name: 'Relaxo Footwears', symbol: 'RELAXO', exchange: 'BSE', ticker: 'RELAXO.BO', currency: '₹' },
  { name: 'Campus Activewear', symbol: 'CAMPUS', exchange: 'BSE', ticker: 'CAMPUS.BO', currency: '₹' },
  { name: 'Kajaria Ceramics', symbol: 'KAJARIACER', exchange: 'BSE', ticker: 'KAJARIACER.BO', currency: '₹' },
  { name: 'Cera Sanitaryware', symbol: 'CERA', exchange: 'BSE', ticker: 'CERA.BO', currency: '₹' },
  { name: 'Century Plyboards', symbol: 'CENTURYPLY', exchange: 'BSE', ticker: 'CENTURYPLY.BO', currency: '₹' },

  // Textiles, Apparels & Retail (BSE)
  { name: 'Page Industries', symbol: 'PAGEIND', exchange: 'BSE', ticker: 'PAGEIND.BO', currency: '₹' },
  { name: 'KPR Mill', symbol: 'KPRMILL', exchange: 'BSE', ticker: 'KPRMILL.BO', currency: '₹' },
  { name: 'Trident', symbol: 'TRIDENT', exchange: 'BSE', ticker: 'TRIDENT.BO', currency: '₹' },
  { name: 'Welspun Living', symbol: 'WELSPUNLIV', exchange: 'BSE', ticker: 'WELSPUNLIV.BO', currency: '₹' },
  { name: 'Vardhman Textiles', symbol: 'VTL', exchange: 'BSE', ticker: 'VTL.BO', currency: '₹' },
  { name: 'Raymond', symbol: 'RAYMOND', exchange: 'BSE', ticker: 'RAYMOND.BO', currency: '₹' },
  { name: 'Arvind', symbol: 'ARVIND', exchange: 'BSE', ticker: 'ARVIND.BO', currency: '₹' },
  { name: 'Shoppers Stop', symbol: 'SHOPPERS', exchange: 'BSE', ticker: 'SHOPPERS.BO', currency: '₹' },
  { name: 'Nykaa', symbol: 'NYKAA', exchange: 'BSE', ticker: 'NYKAA.BO', currency: '₹' },
  { name: 'Bikaji Foods', symbol: 'BIKAJI', exchange: 'BSE', ticker: 'BIKAJI.BO', currency: '₹' },

  // Media, Entertainment & Hospitality (BSE)
  { name: 'Zee Entertainment', symbol: 'ZEEL', exchange: 'BSE', ticker: 'ZEEL.BO', currency: '₹' },
  { name: 'Sun TV', symbol: 'SUNTV', exchange: 'BSE', ticker: 'SUNTV.BO', currency: '₹' },
  { name: 'PVR INOX', symbol: 'PVRINOX', exchange: 'BSE', ticker: 'PVRINOX.BO', currency: '₹' },
  { name: 'Saregama India', symbol: 'SAREGAMA', exchange: 'BSE', ticker: 'SAREGAMA.BO', currency: '₹' },
  { name: 'Network18', symbol: 'NETWORK18', exchange: 'BSE', ticker: 'NETWORK18.BO', currency: '₹' },
  { name: 'Indian Hotels', symbol: 'INDHOTEL', exchange: 'BSE', ticker: 'INDHOTEL.BO', currency: '₹' },
  { name: 'Chalet Hotels', symbol: 'CHALET', exchange: 'BSE', ticker: 'CHALET.BO', currency: '₹' },
  { name: 'Lemon Tree Hotels', symbol: 'LEMONTREE', exchange: 'BSE', ticker: 'LEMONTREE.BO', currency: '₹' },
  { name: 'EIH Ltd', symbol: 'EIHOTEL', exchange: 'BSE', ticker: 'EIHOTEL.BO', currency: '₹' },

  // Midcap Pharma & Healthcare (BSE)
  { name: 'Abbott India', symbol: 'ABBOTINDIA', exchange: 'BSE', ticker: 'ABBOTINDIA.BO', currency: '₹' },
  { name: 'Alkem Laboratories', symbol: 'ALKEM', exchange: 'BSE', ticker: 'ALKEM.BO', currency: '₹' },
  { name: 'Ajanta Pharma', symbol: 'AJANTPHARM', exchange: 'BSE', ticker: 'AJANTPHARM.BO', currency: '₹' },
  { name: 'IPCA Labs', symbol: 'IPCALAB', exchange: 'BSE', ticker: 'IPCALAB.BO', currency: '₹' },
  { name: 'JB Chemicals', symbol: 'JBCHEPHARM', exchange: 'BSE', ticker: 'JBCHEPHARM.BO', currency: '₹' },
  { name: 'Natco Pharma', symbol: 'NATCOPHARM', exchange: 'BSE', ticker: 'NATCOPHARM.BO', currency: '₹' },
  { name: 'Sanofi India', symbol: 'SANOFI', exchange: 'BSE', ticker: 'SANOFI.BO', currency: '₹' },
  { name: 'Pfizer India', symbol: 'PFIZER', exchange: 'BSE', ticker: 'PFIZER.BO', currency: '₹' },
  { name: 'GlaxoSmithKline', symbol: 'GLAXO', exchange: 'BSE', ticker: 'GLAXO.BO', currency: '₹' },
  { name: 'AstraZeneca India', symbol: 'ASTRAZEN', exchange: 'BSE', ticker: 'ASTRAZEN.BO', currency: '₹' },
  { name: 'Metropolis Healthcare', symbol: 'METROPOLIS', exchange: 'BSE', ticker: 'METROPOLIS.BO', currency: '₹' },
  { name: 'Dr. Lal PathLabs', symbol: 'LALPATHLAB', exchange: 'BSE', ticker: 'LALPATHLAB.BO', currency: '₹' },

  // Capital Goods, Engineering & Manufacturing (BSE)
  { name: 'Siemens India', symbol: 'SIEMENS', exchange: 'BSE', ticker: 'SIEMENS.BO', currency: '₹' },
  { name: 'ABB India', symbol: 'ABB', exchange: 'BSE', ticker: 'ABB.BO', currency: '₹' },
  { name: 'CG Power', symbol: 'CGPOWER', exchange: 'BSE', ticker: 'CGPOWER.BO', currency: '₹' },
  { name: 'KEC International', symbol: 'KEC', exchange: 'BSE', ticker: 'KEC.BO', currency: '₹' },
  { name: 'Kalpataru Projects', symbol: 'KPIL', exchange: 'BSE', ticker: 'KPIL.BO', currency: '₹' },
  { name: 'Thermax', symbol: 'THERMAX', exchange: 'BSE', ticker: 'THERMAX.BO', currency: '₹' },
  { name: 'Honeywell Auto', symbol: 'HONAUT', exchange: 'BSE', ticker: 'HONAUT.BO', currency: '₹' },
  { name: 'Triveni Turbine', symbol: 'TRITURBINE', exchange: 'BSE', ticker: 'TRITURBINE.BO', currency: '₹' },
  { name: 'SKF India', symbol: 'SKFINDIA', exchange: 'BSE', ticker: 'SKFINDIA.BO', currency: '₹' },
  { name: 'Timken India', symbol: 'TIMKEN', exchange: 'BSE', ticker: 'TIMKEN.BO', currency: '₹' },
  
  // Fertilizers & Midcap Chemicals (BSE)
  { name: 'Chambal Fertilisers', symbol: 'CHAMBLFERT', exchange: 'BSE', ticker: 'CHAMBLFERT.BO', currency: '₹' },
  { name: 'GNFC', symbol: 'GNFC', exchange: 'BSE', ticker: 'GNFC.BO', currency: '₹' },
  { name: 'GSFC', symbol: 'GSFC', exchange: 'BSE', ticker: 'GSFC.BO', currency: '₹' },
  { name: 'RCF', symbol: 'RCF', exchange: 'BSE', ticker: 'RCF.BO', currency: '₹' },
  { name: 'FACT', symbol: 'FACT', exchange: 'BSE', ticker: 'FACT.BO', currency: '₹' },
  { name: 'Atul Ltd', symbol: 'ATUL', exchange: 'BSE', ticker: 'ATUL.BO', currency: '₹' },
  { name: 'Gujarat Fluorochem', symbol: 'FLUOROCHEM', exchange: 'BSE', ticker: 'FLUOROCHEM.BO', currency: '₹' },
  { name: 'Castrol India', symbol: 'CASTROLIND', exchange: 'BSE', ticker: 'CASTROLIND.BO', currency: '₹' },
  // frontend/app/stocks.ts
// NASDAQ BATCH 1 (125 Stocks)

  // Mega-Cap Tech & Internet (NASDAQ)
  { name: 'Apple', symbol: 'AAPL', exchange: 'NASDAQ', ticker: 'AAPL', currency: '$' },
  { name: 'Microsoft', symbol: 'MSFT', exchange: 'NASDAQ', ticker: 'MSFT', currency: '$' },
  { name: 'Nvidia', symbol: 'NVDA', exchange: 'NASDAQ', ticker: 'NVDA', currency: '$' },
  { name: 'Alphabet Class A', symbol: 'GOOGL', exchange: 'NASDAQ', ticker: 'GOOGL', currency: '$' },
  { name: 'Alphabet Class C', symbol: 'GOOG', exchange: 'NASDAQ', ticker: 'GOOG', currency: '$' },
  { name: 'Amazon', symbol: 'AMZN', exchange: 'NASDAQ', ticker: 'AMZN', currency: '$' },
  { name: 'Meta Platforms', symbol: 'META', exchange: 'NASDAQ', ticker: 'META', currency: '$' },
  { name: 'Tesla', symbol: 'TSLA', exchange: 'NASDAQ', ticker: 'TSLA', currency: '$' },
  { name: 'Netflix', symbol: 'NFLX', exchange: 'NASDAQ', ticker: 'NFLX', currency: '$' },
  { name: 'Adobe', symbol: 'ADBE', exchange: 'NASDAQ', ticker: 'ADBE', currency: '$' },
  { name: 'PayPal', symbol: 'PYPL', exchange: 'NASDAQ', ticker: 'PYPL', currency: '$' },
  { name: 'Airbnb', symbol: 'ABNB', exchange: 'NASDAQ', ticker: 'ABNB', currency: '$' },
  { name: 'Zoom Video', symbol: 'ZM', exchange: 'NASDAQ', ticker: 'ZM', currency: '$' },
  { name: 'Pinterest', symbol: 'PINS', exchange: 'NASDAQ', ticker: 'PINS', currency: '$' },
  { name: 'Snap Inc.', symbol: 'SNAP', exchange: 'NASDAQ', ticker: 'SNAP', currency: '$' },
  { name: 'Roku', symbol: 'ROKU', exchange: 'NASDAQ', ticker: 'ROKU', currency: '$' },
  { name: 'eBay', symbol: 'EBAY', exchange: 'NASDAQ', ticker: 'EBAY', currency: '$' },
  { name: 'Etsy', symbol: 'ETSY', exchange: 'NASDAQ', ticker: 'ETSY', currency: '$' },
  { name: 'Match Group', symbol: 'MTCH', exchange: 'NASDAQ', ticker: 'MTCH', currency: '$' },

  // Semiconductors & Hardware (NASDAQ)
  { name: 'Broadcom', symbol: 'AVGO', exchange: 'NASDAQ', ticker: 'AVGO', currency: '$' },
  { name: 'AMD', symbol: 'AMD', exchange: 'NASDAQ', ticker: 'AMD', currency: '$' },
  { name: 'Intel', symbol: 'INTC', exchange: 'NASDAQ', ticker: 'INTC', currency: '$' },
  { name: 'Qualcomm', symbol: 'QCOM', exchange: 'NASDAQ', ticker: 'QCOM', currency: '$' },
  { name: 'Texas Instruments', symbol: 'TXN', exchange: 'NASDAQ', ticker: 'TXN', currency: '$' },
  { name: 'Applied Materials', symbol: 'AMAT', exchange: 'NASDAQ', ticker: 'AMAT', currency: '$' },
  { name: 'Micron Technology', symbol: 'MU', exchange: 'NASDAQ', ticker: 'MU', currency: '$' },
  { name: 'Lam Research', symbol: 'LRCX', exchange: 'NASDAQ', ticker: 'LRCX', currency: '$' },
  { name: 'KLA Corporation', symbol: 'KLAC', exchange: 'NASDAQ', ticker: 'KLAC', currency: '$' },
  { name: 'NXP Semiconductors', symbol: 'NXPI', exchange: 'NASDAQ', ticker: 'NXPI', currency: '$' },
  { name: 'Microchip Tech', symbol: 'MCHP', exchange: 'NASDAQ', ticker: 'MCHP', currency: '$' },
  { name: 'Marvell Tech', symbol: 'MRVL', exchange: 'NASDAQ', ticker: 'MRVL', currency: '$' },
  { name: 'ASML Holding', symbol: 'ASML', exchange: 'NASDAQ', ticker: 'ASML', currency: '$' },
  { name: 'Arm Holdings', symbol: 'ARM', exchange: 'NASDAQ', ticker: 'ARM', currency: '$' },
  { name: 'Skyworks Solutions', symbol: 'SWKS', exchange: 'NASDAQ', ticker: 'SWKS', currency: '$' },
  { name: 'Qorvo', symbol: 'QRVO', exchange: 'NASDAQ', ticker: 'QRVO', currency: '$' },
  { name: 'Western Digital', symbol: 'WDC', exchange: 'NASDAQ', ticker: 'WDC', currency: '$' },
  { name: 'Seagate Technology', symbol: 'STX', exchange: 'NASDAQ', ticker: 'STX', currency: '$' },

  // Software & Cloud Computing (NASDAQ)
  { name: 'Intuit', symbol: 'INTU', exchange: 'NASDAQ', ticker: 'INTU', currency: '$' },
  { name: 'Workday', symbol: 'WDAY', exchange: 'NASDAQ', ticker: 'WDAY', currency: '$' },
  { name: 'Synopsys', symbol: 'SNPS', exchange: 'NASDAQ', ticker: 'SNPS', currency: '$' },
  { name: 'Cadence Design', symbol: 'CDNS', exchange: 'NASDAQ', ticker: 'CDNS', currency: '$' },
  { name: 'Palo Alto Networks', symbol: 'PANW', exchange: 'NASDAQ', ticker: 'PANW', currency: '$' },
  { name: 'CrowdStrike', symbol: 'CRWD', exchange: 'NASDAQ', ticker: 'CRWD', currency: '$' },
  { name: 'Fortinet', symbol: 'FTNT', exchange: 'NASDAQ', ticker: 'FTNT', currency: '$' },
  { name: 'Atlassian', symbol: 'TEAM', exchange: 'NASDAQ', ticker: 'TEAM', currency: '$' },
  { name: 'Cloudflare', symbol: 'NET', exchange: 'NASDAQ', ticker: 'NET', currency: '$' },
  { name: 'Datadog', symbol: 'DDOG', exchange: 'NASDAQ', ticker: 'DDOG', currency: '$' },
  { name: 'MongoDB', symbol: 'MDB', exchange: 'NASDAQ', ticker: 'MDB', currency: '$' },
  { name: 'Okta', symbol: 'OKTA', exchange: 'NASDAQ', ticker: 'OKTA', currency: '$' },
  { name: 'Zscaler', symbol: 'ZS', exchange: 'NASDAQ', ticker: 'ZS', currency: '$' },
  { name: 'Splunk', symbol: 'SPLK', exchange: 'NASDAQ', ticker: 'SPLK', currency: '$' },
  { name: 'DocuSign', symbol: 'DOCU', exchange: 'NASDAQ', ticker: 'DOCU', currency: '$' },
  { name: 'Snowflake', symbol: 'SNOW', exchange: 'NASDAQ', ticker: 'SNOW', currency: '$' },
  { name: 'AppLovin', symbol: 'APP', exchange: 'NASDAQ', ticker: 'APP', currency: '$' },

  // Biotech & Healthcare (NASDAQ)
  { name: 'Amgen', symbol: 'AMGN', exchange: 'NASDAQ', ticker: 'AMGN', currency: '$' },
  { name: 'Gilead Sciences', symbol: 'GILD', exchange: 'NASDAQ', ticker: 'GILD', currency: '$' },
  { name: 'Vertex Pharmaceuticals', symbol: 'VRTX', exchange: 'NASDAQ', ticker: 'VRTX', currency: '$' },
  { name: 'Regeneron Pharma', symbol: 'REGN', exchange: 'NASDAQ', ticker: 'REGN', currency: '$' },
  { name: 'Biogen', symbol: 'BIIB', exchange: 'NASDAQ', ticker: 'BIIB', currency: '$' },
  { name: 'Illumina', symbol: 'ILMN', exchange: 'NASDAQ', ticker: 'ILMN', currency: '$' },
  { name: 'Align Technology', symbol: 'ALGN', exchange: 'NASDAQ', ticker: 'ALGN', currency: '$' },
  { name: 'IDEXX Laboratories', symbol: 'IDXX', exchange: 'NASDAQ', ticker: 'IDXX', currency: '$' },
  { name: 'DexCom', symbol: 'DXCM', exchange: 'NASDAQ', ticker: 'DXCM', currency: '$' },
  { name: 'Moderna', symbol: 'MRNA', exchange: 'NASDAQ', ticker: 'MRNA', currency: '$' },
  { name: 'Incyte', symbol: 'INCY', exchange: 'NASDAQ', ticker: 'INCY', currency: '$' },
  { name: 'Exact Sciences', symbol: 'EXAS', exchange: 'NASDAQ', ticker: 'EXAS', currency: '$' },
  { name: 'Intellia Therapeutics', symbol: 'NTLA', exchange: 'NASDAQ', ticker: 'NTLA', currency: '$' },
  { name: 'CRISPR Therapeutics', symbol: 'CRSP', exchange: 'NASDAQ', ticker: 'CRSP', currency: '$' },
  { name: 'Viatris', symbol: 'VTRS', exchange: 'NASDAQ', ticker: 'VTRS', currency: '$' },

  // Consumer, Retail & Food (NASDAQ)
  { name: 'Costco Wholesale', symbol: 'COST', exchange: 'NASDAQ', ticker: 'COST', currency: '$' },
  { name: 'PepsiCo', symbol: 'PEP', exchange: 'NASDAQ', ticker: 'PEP', currency: '$' },
  { name: 'Starbucks', symbol: 'SBUX', exchange: 'NASDAQ', ticker: 'SBUX', currency: '$' },
  { name: 'Mondelez Int.', symbol: 'MDLZ', exchange: 'NASDAQ', ticker: 'MDLZ', currency: '$' },
  { name: 'Monster Beverage', symbol: 'MNST', exchange: 'NASDAQ', ticker: 'MNST', currency: '$' },
  { name: 'Kraft Heinz', symbol: 'KHC', exchange: 'NASDAQ', ticker: 'KHC', currency: '$' },
  { name: 'Keurig Dr Pepper', symbol: 'KDP', exchange: 'NASDAQ', ticker: 'KDP', currency: '$' },
  { name: 'Ross Stores', symbol: 'ROST', exchange: 'NASDAQ', ticker: 'ROST', currency: '$' },
  { name: 'O\'Reilly Auto Parts', symbol: 'ORLY', exchange: 'NASDAQ', ticker: 'ORLY', currency: '$' },
  { name: 'Tractor Supply', symbol: 'TSCO', exchange: 'NASDAQ', ticker: 'TSCO', currency: '$' },
  { name: 'Lululemon', symbol: 'LULU', exchange: 'NASDAQ', ticker: 'LULU', currency: '$' },
  { name: 'Ulta Beauty', symbol: 'ULTA', exchange: 'NASDAQ', ticker: 'ULTA', currency: '$' },
  { name: 'Marriott Int.', symbol: 'MAR', exchange: 'NASDAQ', ticker: 'MAR', currency: '$' },
  { name: 'Hasbro', symbol: 'HAS', exchange: 'NASDAQ', ticker: 'HAS', currency: '$' },
  { name: 'Fox Corporation', symbol: 'FOXA', exchange: 'NASDAQ', ticker: 'FOXA', currency: '$' },
  { name: 'Warner Bros. Discovery', symbol: 'WBD', exchange: 'NASDAQ', ticker: 'WBD', currency: '$' },
  { name: 'Sirius XM', symbol: 'SIRI', exchange: 'NASDAQ', ticker: 'SIRI', currency: '$' },

  // Industrial, Transport & Financial Tech (NASDAQ)
  { name: 'CSX Corporation', symbol: 'CSX', exchange: 'NASDAQ', ticker: 'CSX', currency: '$' },
  { name: 'PACCAR', symbol: 'PCAR', exchange: 'NASDAQ', ticker: 'PCAR', currency: '$' },
  { name: 'Old Dominion Freight', symbol: 'ODFL', exchange: 'NASDAQ', ticker: 'ODFL', currency: '$' },
  { name: 'Fastenal', symbol: 'FAST', exchange: 'NASDAQ', ticker: 'FAST', currency: '$' },
  { name: 'Cintas', symbol: 'CTAS', exchange: 'NASDAQ', ticker: 'CTAS', currency: '$' },
  { name: 'Paychex', symbol: 'PAYX', exchange: 'NASDAQ', ticker: 'PAYX', currency: '$' },
  { name: 'Verisk Analytics', symbol: 'VRSK', exchange: 'NASDAQ', ticker: 'VRSK', currency: '$' },
  { name: 'ADP', symbol: 'ADP', exchange: 'NASDAQ', ticker: 'ADP', currency: '$' },
  { name: 'Exelon', symbol: 'EXC', exchange: 'NASDAQ', ticker: 'EXC', currency: '$' },
  { name: 'Xcel Energy', symbol: 'XEL', exchange: 'NASDAQ', ticker: 'XEL', currency: '$' },
  { name: 'American Electric', symbol: 'AEP', exchange: 'NASDAQ', ticker: 'AEP', currency: '$' },
  { name: 'CDW Corporation', symbol: 'CDW', exchange: 'NASDAQ', ticker: 'CDW', currency: '$' },
  { name: 'Charter Communications', symbol: 'CHTR', exchange: 'NASDAQ', ticker: 'CHTR', currency: '$' },
  { name: 'Copart', symbol: 'CPRT', exchange: 'NASDAQ', ticker: 'CPRT', currency: '$' },
  { name: 'Coinbase', symbol: 'COIN', exchange: 'NASDAQ', ticker: 'COIN', currency: '$' },
  { name: 'Robinhood', symbol: 'HOOD', exchange: 'NASDAQ', ticker: 'HOOD', currency: '$' },
  { name: 'SoFi Technologies', symbol: 'SOFI', exchange: 'NASDAQ', ticker: 'SOFI', currency: '$' },
  { name: 'Affirm', symbol: 'AFRM', exchange: 'NASDAQ', ticker: 'AFRM', currency: '$' },

  // Emerging Tech, Energy & ADRs (NASDAQ)
  { name: 'First Solar', symbol: 'FSLR', exchange: 'NASDAQ', ticker: 'FSLR', currency: '$' },
  { name: 'Enphase Energy', symbol: 'ENPH', exchange: 'NASDAQ', ticker: 'ENPH', currency: '$' },
  { name: 'SolarEdge', symbol: 'SEDG', exchange: 'NASDAQ', ticker: 'SEDG', currency: '$' },
  { name: 'Plug Power', symbol: 'PLUG', exchange: 'NASDAQ', ticker: 'PLUG', currency: '$' },
  { name: 'Sunrun', symbol: 'RUN', exchange: 'NASDAQ', ticker: 'RUN', currency: '$' },
  { name: 'Rivian', symbol: 'RIVN', exchange: 'NASDAQ', ticker: 'RIVN', currency: '$' },
  { name: 'Lucid Group', symbol: 'LCID', exchange: 'NASDAQ', ticker: 'LCID', currency: '$' },
  { name: 'PDD Holdings', symbol: 'PDD', exchange: 'NASDAQ', ticker: 'PDD', currency: '$' },
  { name: 'JD.com', symbol: 'JD', exchange: 'NASDAQ', ticker: 'JD', currency: '$' },
  { name: 'Baidu', symbol: 'BIDU', exchange: 'NASDAQ', ticker: 'BIDU', currency: '$' },
  { name: 'NetEase', symbol: 'NTES', exchange: 'NASDAQ', ticker: 'NTES', currency: '$' },
  { name: 'Trip.com', symbol: 'TCOM', exchange: 'NASDAQ', ticker: 'TCOM', currency: '$' },
  { name: 'Bilibili', symbol: 'BILI', exchange: 'NASDAQ', ticker: 'BILI', currency: '$' },
  { name: 'MercadoLibre', symbol: 'MELI', exchange: 'NASDAQ', ticker: 'MELI', currency: '$' },
  // frontend/app/stocks.ts
// US STOCKS BATCH 2 (125 Stocks)

  // Financials & Mega-Banks (NYSE)
  { name: 'Bank of America', symbol: 'BAC', exchange: 'NYSE', ticker: 'BAC', currency: '$' },
  { name: 'Wells Fargo', symbol: 'WFC', exchange: 'NYSE', ticker: 'WFC', currency: '$' },
  { name: 'Citigroup', symbol: 'C', exchange: 'NYSE', ticker: 'C', currency: '$' },
  { name: 'Goldman Sachs', symbol: 'GS', exchange: 'NYSE', ticker: 'GS', currency: '$' },
  { name: 'Morgan Stanley', symbol: 'MS', exchange: 'NYSE', ticker: 'MS', currency: '$' },
  { name: 'American Express', symbol: 'AXP', exchange: 'NYSE', ticker: 'AXP', currency: '$' },
  { name: 'BlackRock', symbol: 'BLK', exchange: 'NYSE', ticker: 'BLK', currency: '$' },
  { name: 'Charles Schwab', symbol: 'SCHW', exchange: 'NYSE', ticker: 'SCHW', currency: '$' },
  { name: 'S&P Global', symbol: 'SPGI', exchange: 'NYSE', ticker: 'SPGI', currency: '$' },
  { name: 'CME Group', symbol: 'CME', exchange: 'NASDAQ', ticker: 'CME', currency: '$' },
  { name: 'Marsh & McLennan', symbol: 'MMC', exchange: 'NYSE', ticker: 'MMC', currency: '$' },
  { name: 'Aon', symbol: 'AON', exchange: 'NYSE', ticker: 'AON', currency: '$' },
  { name: 'Chubb', symbol: 'CB', exchange: 'NYSE', ticker: 'CB', currency: '$' },
  { name: 'Progressive', symbol: 'PGR', exchange: 'NYSE', ticker: 'PGR', currency: '$' },
  { name: 'U.S. Bancorp', symbol: 'USB', exchange: 'NYSE', ticker: 'USB', currency: '$' },
  { name: 'PNC Financial', symbol: 'PNC', exchange: 'NYSE', ticker: 'PNC', currency: '$' },
  { name: 'Truist Financial', symbol: 'TFC', exchange: 'NYSE', ticker: 'TFC', currency: '$' },
  { name: 'Capital One', symbol: 'COF', exchange: 'NYSE', ticker: 'COF', currency: '$' },
  { name: 'Bank of New York Mellon', symbol: 'BK', exchange: 'NYSE', ticker: 'BK', currency: '$' },
  { name: 'State Street', symbol: 'STT', exchange: 'NYSE', ticker: 'STT', currency: '$' },
  { name: 'Discover Financial', symbol: 'DFS', exchange: 'NYSE', ticker: 'DFS', currency: '$' },
  { name: 'Synchrony Financial', symbol: 'SYF', exchange: 'NYSE', ticker: 'SYF', currency: '$' },

  // Healthcare, Pharma & Medical Devices (NYSE/NASDAQ)
  { name: 'Johnson & Johnson', symbol: 'JNJ', exchange: 'NYSE', ticker: 'JNJ', currency: '$' },
  { name: 'Pfizer', symbol: 'PFE', exchange: 'NYSE', ticker: 'PFE', currency: '$' },
  { name: 'Merck', symbol: 'MRK', exchange: 'NYSE', ticker: 'MRK', currency: '$' },
  { name: 'AbbVie', symbol: 'ABBV', exchange: 'NYSE', ticker: 'ABBV', currency: '$' },
  { name: 'Thermo Fisher Scientific', symbol: 'TMO', exchange: 'NYSE', ticker: 'TMO', currency: '$' },
  { name: 'Danaher', symbol: 'DHR', exchange: 'NYSE', ticker: 'DHR', currency: '$' },
  { name: 'Abbott Laboratories', symbol: 'ABT', exchange: 'NYSE', ticker: 'ABT', currency: '$' },
  { name: 'Bristol-Myers Squibb', symbol: 'BMY', exchange: 'NYSE', ticker: 'BMY', currency: '$' },
  { name: 'CVS Health', symbol: 'CVS', exchange: 'NYSE', ticker: 'CVS', currency: '$' },
  { name: 'Cigna', symbol: 'CI', exchange: 'NYSE', ticker: 'CI', currency: '$' },
  { name: 'Humana', symbol: 'HUM', exchange: 'NYSE', ticker: 'HUM', currency: '$' },
  { name: 'Centene', symbol: 'CNC', exchange: 'NYSE', ticker: 'CNC', currency: '$' },
  { name: 'McKesson', symbol: 'MCK', exchange: 'NYSE', ticker: 'MCK', currency: '$' },
  { name: 'Cardinal Health', symbol: 'CAH', exchange: 'NYSE', ticker: 'CAH', currency: '$' },
  { name: 'Boston Scientific', symbol: 'BSX', exchange: 'NYSE', ticker: 'BSX', currency: '$' },
  { name: 'Stryker', symbol: 'SYK', exchange: 'NYSE', ticker: 'SYK', currency: '$' },
  { name: 'Medtronic', symbol: 'MDT', exchange: 'NYSE', ticker: 'MDT', currency: '$' },
  { name: 'Edwards Lifesciences', symbol: 'EW', exchange: 'NYSE', ticker: 'EW', currency: '$' },
  { name: 'Intuitive Surgical', symbol: 'ISRG', exchange: 'NASDAQ', ticker: 'ISRG', currency: '$' },
  { name: 'Becton Dickinson', symbol: 'BDX', exchange: 'NYSE', ticker: 'BDX', currency: '$' },

  // Industrials, Defense & Aerospace (NYSE)
  { name: 'Boeing', symbol: 'BA', exchange: 'NYSE', ticker: 'BA', currency: '$' },
  { name: 'Lockheed Martin', symbol: 'LMT', exchange: 'NYSE', ticker: 'LMT', currency: '$' },
  { name: 'RTX Corp (Raytheon)', symbol: 'RTX', exchange: 'NYSE', ticker: 'RTX', currency: '$' },
  { name: 'General Dynamics', symbol: 'GD', exchange: 'NYSE', ticker: 'GD', currency: '$' },
  { name: 'Northrop Grumman', symbol: 'NOC', exchange: 'NYSE', ticker: 'NOC', currency: '$' },
  { name: 'Honeywell', symbol: 'HON', exchange: 'NASDAQ', ticker: 'HON', currency: '$' },
  { name: '3M', symbol: 'MMM', exchange: 'NYSE', ticker: 'MMM', currency: '$' },
  { name: 'General Electric', symbol: 'GE', exchange: 'NYSE', ticker: 'GE', currency: '$' },
  { name: 'Caterpillar', symbol: 'CAT', exchange: 'NYSE', ticker: 'CAT', currency: '$' },
  { name: 'Deere & Co', symbol: 'DE', exchange: 'NYSE', ticker: 'DE', currency: '$' },
  { name: 'Emerson Electric', symbol: 'EMR', exchange: 'NYSE', ticker: 'EMR', currency: '$' },
  { name: 'Eaton', symbol: 'ETN', exchange: 'NYSE', ticker: 'ETN', currency: '$' },
  { name: 'Parker-Hannifin', symbol: 'PH', exchange: 'NYSE', ticker: 'PH', currency: '$' },
  { name: 'Roper Technologies', symbol: 'ROP', exchange: 'NASDAQ', ticker: 'ROP', currency: '$' },
  { name: 'Cummins', symbol: 'CMI', exchange: 'NYSE', ticker: 'CMI', currency: '$' },
  { name: 'FedEx', symbol: 'FDX', exchange: 'NYSE', ticker: 'FDX', currency: '$' },
  { name: 'United Parcel Service', symbol: 'UPS', exchange: 'NYSE', ticker: 'UPS', currency: '$' },
  { name: 'Union Pacific', symbol: 'UNP', exchange: 'NYSE', ticker: 'UNP', currency: '$' },
  { name: 'Norfolk Southern', symbol: 'NSC', exchange: 'NYSE', ticker: 'NSC', currency: '$' },

  // Energy & Oil (NYSE)
  { name: 'Exxon Mobil', symbol: 'XOM', exchange: 'NYSE', ticker: 'XOM', currency: '$' },
  { name: 'Chevron', symbol: 'CVX', exchange: 'NYSE', ticker: 'CVX', currency: '$' },
  { name: 'ConocoPhillips', symbol: 'COP', exchange: 'NYSE', ticker: 'COP', currency: '$' },
  { name: 'EOG Resources', symbol: 'EOG', exchange: 'NYSE', ticker: 'EOG', currency: '$' },
  { name: 'Occidental Petroleum', symbol: 'OXY', exchange: 'NYSE', ticker: 'OXY', currency: '$' },
  { name: 'Marathon Petroleum', symbol: 'MPC', exchange: 'NYSE', ticker: 'MPC', currency: '$' },
  { name: 'Phillips 66', symbol: 'PSX', exchange: 'NYSE', ticker: 'PSX', currency: '$' },
  { name: 'Valero Energy', symbol: 'VLO', exchange: 'NYSE', ticker: 'VLO', currency: '$' },
  { name: 'Schlumberger', symbol: 'SLB', exchange: 'NYSE', ticker: 'SLB', currency: '$' },
  { name: 'Halliburton', symbol: 'HAL', exchange: 'NYSE', ticker: 'HAL', currency: '$' },
  { name: 'Baker Hughes', symbol: 'BKR', exchange: 'NASDAQ', ticker: 'BKR', currency: '$' },
  { name: 'Williams Companies', symbol: 'WMB', exchange: 'NYSE', ticker: 'WMB', currency: '$' },
  { name: 'Kinder Morgan', symbol: 'KMI', exchange: 'NYSE', ticker: 'KMI', currency: '$' },
  { name: 'ONEOK', symbol: 'OKE', exchange: 'NYSE', ticker: 'OKE', currency: '$' },

  // Consumer Discretionary & Retail (NYSE)
  { name: 'Walmart', symbol: 'WMT', exchange: 'NYSE', ticker: 'WMT', currency: '$' },
  { name: 'Target', symbol: 'TGT', exchange: 'NYSE', ticker: 'TGT', currency: '$' },
  { name: 'Home Depot', symbol: 'HD', exchange: 'NYSE', ticker: 'HD', currency: '$' },
  { name: 'Lowe\'s', symbol: 'LOW', exchange: 'NYSE', ticker: 'LOW', currency: '$' },
  { name: 'McDonald\'s', symbol: 'MCD', exchange: 'NYSE', ticker: 'MCD', currency: '$' },
  { name: 'Nike', symbol: 'NKE', exchange: 'NYSE', ticker: 'NKE', currency: '$' },
  { name: 'TJX Companies', symbol: 'TJX', exchange: 'NYSE', ticker: 'TJX', currency: '$' },
  { name: 'Yum! Brands', symbol: 'YUM', exchange: 'NYSE', ticker: 'YUM', currency: '$' },
  { name: 'Darden Restaurants', symbol: 'DRI', exchange: 'NYSE', ticker: 'DRI', currency: '$' },
  { name: 'Chipotle', symbol: 'CMG', exchange: 'NYSE', ticker: 'CMG', currency: '$' },
  { name: 'AutoZone', symbol: 'AZO', exchange: 'NYSE', ticker: 'AZO', currency: '$' },

  // Telecom, Media & Entertainment (NYSE/NASDAQ)
  { name: 'AT&T', symbol: 'T', exchange: 'NYSE', ticker: 'T', currency: '$' },
  { name: 'Verizon', symbol: 'VZ', exchange: 'NYSE', ticker: 'VZ', currency: '$' },
  { name: 'T-Mobile', symbol: 'TMUS', exchange: 'NASDAQ', ticker: 'TMUS', currency: '$' },
  { name: 'Walt Disney', symbol: 'DIS', exchange: 'NYSE', ticker: 'DIS', currency: '$' },
  { name: 'Comcast', symbol: 'CMCSA', exchange: 'NASDAQ', ticker: 'CMCSA', currency: '$' },
  { name: 'Live Nation', symbol: 'LYV', exchange: 'NYSE', ticker: 'LYV', currency: '$' },
  { name: 'Omnicom Group', symbol: 'OMC', exchange: 'NYSE', ticker: 'OMC', currency: '$' },
  { name: 'Interpublic Group', symbol: 'IPG', exchange: 'NYSE', ticker: 'IPG', currency: '$' },

  // Materials & Chemicals (NYSE)
  { name: 'Linde', symbol: 'LIN', exchange: 'NYSE', ticker: 'LIN', currency: '$' },
  { name: 'Air Products', symbol: 'APD', exchange: 'NYSE', ticker: 'APD', currency: '$' },
  { name: 'Ecolab', symbol: 'ECL', exchange: 'NYSE', ticker: 'ECL', currency: '$' },
  { name: 'Sherwin-Williams', symbol: 'SHW', exchange: 'NYSE', ticker: 'SHW', currency: '$' },
  { name: 'PPG Industries', symbol: 'PPG', exchange: 'NYSE', ticker: 'PPG', currency: '$' },
  { name: 'Newmont', symbol: 'NEM', exchange: 'NYSE', ticker: 'NEM', currency: '$' },
  { name: 'Freeport-McMoRan', symbol: 'FCX', exchange: 'NYSE', ticker: 'FCX', currency: '$' },
  { name: 'Nucor', symbol: 'NUE', exchange: 'NYSE', ticker: 'NUE', currency: '$' },
  { name: 'Dow Inc.', symbol: 'DOW', exchange: 'NYSE', ticker: 'DOW', currency: '$' },
  { name: 'DuPont', symbol: 'DD', exchange: 'NYSE', ticker: 'DD', currency: '$' },

  // Real Estate (REITs) (NYSE)
  { name: 'Prologis', symbol: 'PLD', exchange: 'NYSE', ticker: 'PLD', currency: '$' },
  { name: 'American Tower', symbol: 'AMT', exchange: 'NYSE', ticker: 'AMT', currency: '$' },
  { name: 'Crown Castle', symbol: 'CCI', exchange: 'NYSE', ticker: 'CCI', currency: '$' },
  { name: 'Equinix', symbol: 'EQIX', exchange: 'NASDAQ', ticker: 'EQIX', currency: '$' },
  { name: 'Public Storage', symbol: 'PSA', exchange: 'NYSE', ticker: 'PSA', currency: '$' },
  { name: 'Simon Property', symbol: 'SPG', exchange: 'NYSE', ticker: 'SPG', currency: '$' },
  { name: 'Realty Income', symbol: 'O', exchange: 'NYSE', ticker: 'O', currency: '$' },
  { name: 'VICI Properties', symbol: 'VICI', exchange: 'NYSE', ticker: 'VICI', currency: '$' },
  { name: 'Welltower', symbol: 'WELL', exchange: 'NYSE', ticker: 'WELL', currency: '$' },
  { name: 'AvalonBay', symbol: 'AVB', exchange: 'NYSE', ticker: 'AVB', currency: '$' },
  { name: 'Equity Residential', symbol: 'EQR', exchange: 'NYSE', ticker: 'EQR', currency: '$' },

  // Utilities (NYSE)
  { name: 'NextEra Energy', symbol: 'NEE', exchange: 'NYSE', ticker: 'NEE', currency: '$' },
  { name: 'Duke Energy', symbol: 'DUK', exchange: 'NYSE', ticker: 'DUK', currency: '$' },
  { name: 'Southern Company', symbol: 'SO', exchange: 'NYSE', ticker: 'SO', currency: '$' },
  { name: 'Dominion Energy', symbol: 'D', exchange: 'NYSE', ticker: 'D', currency: '$' },
  { name: 'Sempra Energy', symbol: 'SRE', exchange: 'NYSE', ticker: 'SRE', currency: '$' },
  { name: 'Consolidated Edison', symbol: 'ED', exchange: 'NYSE', ticker: 'ED', currency: '$' },
  { name: 'Public Service Ent.', symbol: 'PEG', exchange: 'NYSE', ticker: 'PEG', currency: '$' },
  { name: 'WEC Energy Group', symbol: 'WEC', exchange: 'NYSE', ticker: 'WEC', currency: '$' },
  // ==========================================
  // CRYPTOCURRENCIES
  // ==========================================
  { name: 'Bitcoin', symbol: 'BTC', exchange: 'CRYPTO', ticker: 'BTC-USD', currency: '$' },
  { name: 'Ethereum', symbol: 'ETH', exchange: 'CRYPTO', ticker: 'ETH-USD', currency: '$' },
  { name: 'Tether', symbol: 'USDT', exchange: 'CRYPTO', ticker: 'USDT-USD', currency: '$' },
  { name: 'BNB', symbol: 'BNB', exchange: 'CRYPTO', ticker: 'BNB-USD', currency: '$' },
  { name: 'Solana', symbol: 'SOL', exchange: 'CRYPTO', ticker: 'SOL-USD', currency: '$' },
  { name: 'USDC', symbol: 'USDC', exchange: 'CRYPTO', ticker: 'USDC-USD', currency: '$' },
  { name: 'XRP', symbol: 'XRP', exchange: 'CRYPTO', ticker: 'XRP-USD', currency: '$' },
  { name: 'Cardano', symbol: 'ADA', exchange: 'CRYPTO', ticker: 'ADA-USD', currency: '$' },
  { name: 'Avalanche', symbol: 'AVAX', exchange: 'CRYPTO', ticker: 'AVAX-USD', currency: '$' },
  { name: 'Dogecoin', symbol: 'DOGE', exchange: 'CRYPTO', ticker: 'DOGE-USD', currency: '$' },
  { name: 'Polkadot', symbol: 'DOT', exchange: 'CRYPTO', ticker: 'DOT-USD', currency: '$' },
  { name: 'Tron', symbol: 'TRX', exchange: 'CRYPTO', ticker: 'TRX-USD', currency: '$' },
  { name: 'Chainlink', symbol: 'LINK', exchange: 'CRYPTO', ticker: 'LINK-USD', currency: '$' },
  { name: 'Polygon', symbol: 'MATIC', exchange: 'CRYPTO', ticker: 'MATIC-USD', currency: '$' },
  { name: 'Shiba Inu', symbol: 'SHIB', exchange: 'CRYPTO', ticker: 'SHIB-USD', currency: '$' },
  { name: 'Litecoin', symbol: 'LTC', exchange: 'CRYPTO', ticker: 'LTC-USD', currency: '$' },
  { name: 'Bitcoin Cash', symbol: 'BCH', exchange: 'CRYPTO', ticker: 'BCH-USD', currency: '$' },
  { name: 'Uniswap', symbol: 'UNI', exchange: 'CRYPTO', ticker: 'UNI-USD', currency: '$' },
  { name: 'Cosmos', symbol: 'ATOM', exchange: 'CRYPTO', ticker: 'ATOM-USD', currency: '$' },
  { name: 'Monero', symbol: 'XMR', exchange: 'CRYPTO', ticker: 'XMR-USD', currency: '$' },
  { name: 'Stellar', symbol: 'XLM', exchange: 'CRYPTO', ticker: 'XLM-USD', currency: '$' },
  { name: 'Aptos', symbol: 'APT', exchange: 'CRYPTO', ticker: 'APT-USD', currency: '$' },
  { name: 'Arbitrum', symbol: 'ARB', exchange: 'CRYPTO', ticker: 'ARB-USD', currency: '$' },
  { name: 'NEAR Protocol', symbol: 'NEAR', exchange: 'CRYPTO', ticker: 'NEAR-USD', currency: '$' },
  { name: 'Filecoin', symbol: 'FIL', exchange: 'CRYPTO', ticker: 'FIL-USD', currency: '$' },
  { name: 'Ethereum Classic', symbol: 'ETC', exchange: 'CRYPTO', ticker: 'ETC-USD', currency: '$' },
  { name: 'Optimism', symbol: 'OP', exchange: 'CRYPTO', ticker: 'OP-USD', currency: '$' },
  { name: 'Injective', symbol: 'INJ', exchange: 'CRYPTO', ticker: 'INJ-USD', currency: '$' },
  { name: 'Internet Computer', symbol: 'ICP', exchange: 'CRYPTO', ticker: 'ICP-USD', currency: '$' },
  { name: 'VeChain', symbol: 'VET', exchange: 'CRYPTO', ticker: 'VET-USD', currency: '$' }
];

export const STOCKS = RAW_STOCKS.filter((stock) => stock.exchange !== 'CRYPTO');
